package app

import (
	"bytes"
	"context"
	"denova/config"
	platformapp "denova/internal/app/platform"
	booklore "denova/internal/book/lore"
	"denova/internal/platform"
	"denova/internal/project"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/png"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
)

func TestPlatformResourcesReuseScopedLibraryAndImageProvider(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	var imageData bytes.Buffer
	if err := png.Encode(&imageData, image.NewRGBA(image.Rect(0, 0, 2, 2))); err != nil {
		t.Fatal(err)
	}
	var calls atomic.Int32
	provider := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		calls.Add(1)
		var input struct {
			Model  string `json:"model"`
			Prompt string `json:"prompt"`
			N      int    `json:"n"`
		}
		if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
			t.Error(err)
		}
		if r.URL.Path != "/v1/images/generations" || r.Header.Get("Authorization") != "Bearer test-resource-secret" || input.Model != "test-image-model" || input.Prompt != "A quiet station" || input.N != 1 {
			t.Errorf("unexpected image provider request: %s %#v", r.URL.Path, input)
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": []any{map[string]string{"b64_json": base64.StdEncoding.EncodeToString(imageData.Bytes()), "revised_prompt": "Quiet station"}}})
	}))
	defer provider.Close()
	if err := config.WriteSettingsFile(config.UserConfigPath(root), config.Settings{
		ImageAPIEndpoints: []config.ImageAPIEndpointSettings{{ID: "test-images", Provider: config.ImageProviderOpenAI, Protocol: config.ImageProtocolOpenAI, APIKey: "test-resource-secret", BaseURL: provider.URL + "/v1"}},
		ImageAPIProfiles:  []config.ImageAPIProfileSettings{{ID: "illustrator", EndpointID: "test-images", Model: "test-image-model"}},
	}); err != nil {
		t.Fatal(err)
	}
	application, err := New(ctx, &config.Config{
		DenovaDir: root, OpenAIModel: "test-text-model",
	})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(application.Close)
	projects := []project.Record{}
	for _, name := range []string{"first", "second"} {
		directory := filepath.Join(root, "projects", name)
		if err := os.MkdirAll(directory, 0700); err != nil {
			t.Fatal(err)
		}
		record, err := application.projectRegistry.Add(directory, project.TypeGeneral, name)
		if err != nil {
			t.Fatal(err)
		}
		if _, err := application.projectRegistry.EnsureStore(record); err != nil {
			t.Fatal(err)
		}
		projects = append(projects, record)
		store := booklore.NewStore(directory)
		if _, err := store.Create(booklore.ItemInput{ID: name, Name: name, Type: "character", Content: "The " + name + " character", Image: &booklore.Image{ImagePath: "assets/portrait.png"}}); err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll(filepath.Join(directory, "assets"), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(directory, "assets", "portrait.png"), imageData.Bytes(), 0600); err != nil {
			t.Fatal(err)
		}
	}
	host := platformapp.NewResources(platformHost{application})
	items, err := host.LibraryItems(ctx, projects[1].ID)
	if err != nil || len(items) != 1 || items[0].Name != "second" || items[0].Image == nil || items[0].Image.Path != "assets/portrait.png" {
		t.Fatalf("scoped library: %#v %v", items, err)
	}
	data, err := host.ReadAsset(ctx, projects[1].ID, "assets/portrait.png")
	if err != nil || !bytes.Equal(data, imageData.Bytes()) {
		t.Fatalf("scoped asset: %v", err)
	}
	if _, err := host.ReadAsset(ctx, projects[1].ID, "../first/assets/portrait.png"); err == nil {
		t.Fatal("cross-Project asset traversal succeeded")
	}
	if _, err := host.LibraryItems(ctx, "unknown-project"); err == nil {
		t.Fatal("unknown Project library succeeded")
	}
	generated, err := host.GenerateImage(ctx, projects[1].ID, "illustrator", platform.ImageRequest{CommandID: "scene-1", ModelSlot: "art", Prompt: "A quiet station"})
	if err != nil || !bytes.Equal(generated.Data, imageData.Bytes()) || generated.RevisedPrompt != "Quiet station" || calls.Load() != 1 {
		t.Fatalf("image provider: %#v calls=%d err=%v", generated, calls.Load(), err)
	}
	// Generated bytes return to platform-owned scope storage; source assets and
	// library bindings remain untouched, including General Projects.
	items, err = host.LibraryItems(ctx, projects[1].ID)
	if err != nil || items[0].Image.Path != "assets/portrait.png" {
		t.Fatalf("generation changed library: %#v %v", items, err)
	}
}

func TestPlatformImageOptionsUseNativeDefaultsAndValidation(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	var raster bytes.Buffer
	if err := png.Encode(&raster, image.NewRGBA(image.Rect(0, 0, 2, 2))); err != nil {
		t.Fatal(err)
	}
	type providerInput struct {
		Model, Prompt string
		Size          string `json:"size"`
		OutputFormat  string `json:"output_format"`
	}
	requests := make(chan providerInput, 8)
	provider := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var input providerInput
		if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
			t.Error(err)
		}
		if r.URL.Path != "/v1/images/generations" || r.Header.Get("Authorization") != "Bearer image-options-fixture" {
			t.Errorf("unexpected native provider boundary: %s", r.URL.Path)
		}
		requests <- input
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"data": []any{map[string]string{"b64_json": base64.StdEncoding.EncodeToString(raster.Bytes())}}})
	}))
	defer provider.Close()
	if err := config.WriteSettingsFile(config.UserConfigPath(root), config.Settings{
		ImageAPIEndpoints: []config.ImageAPIEndpointSettings{
			{ID: "ark-fixture", Provider: config.ImageProviderVolcengine, Protocol: config.ImageProtocolArk, APIKey: "image-options-fixture", BaseURL: provider.URL + "/v1"},
			{ID: "xai-fixture", Provider: config.ImageProviderXAI, Protocol: config.ImageProtocolXAI, APIKey: "image-options-fixture", BaseURL: provider.URL + "/v1"},
		},
		ImageAPIProfiles: []config.ImageAPIProfileSettings{
			{ID: "ark", EndpointID: "ark-fixture", Model: "test-ark-image", DefaultResolution: "2K", DefaultOutputFormat: "png"},
			{ID: "xai", EndpointID: "xai-fixture", Model: "test-xai-image"},
		},
	}); err != nil {
		t.Fatal(err)
	}
	application, err := New(ctx, &config.Config{DenovaDir: root, OpenAIModel: "test-text-model"})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(application.Close)
	directory := filepath.Join(root, "image-project")
	if err := os.MkdirAll(directory, 0700); err != nil {
		t.Fatal(err)
	}
	record, err := application.projectRegistry.Add(directory, project.TypeGeneral, "Image options")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := application.projectRegistry.EnsureStore(record); err != nil {
		t.Fatal(err)
	}
	host := platformapp.NewResources(platformHost{application})
	for _, test := range []struct {
		name, size, resolution, format, wantSize, wantFormat string
	}{
		{name: "profile defaults", wantSize: "2K", wantFormat: "png"},
		{name: "explicit resolution and format", resolution: "4K", format: "webp", wantSize: "4K", wantFormat: "webp"},
		{name: "native normalization", resolution: " 1K ", format: " JPG ", wantSize: "1K", wantFormat: "jpeg"},
		{name: "native size precedence", size: "1536x1024", resolution: "4K", format: "png", wantSize: "1536x1024", wantFormat: "png"},
	} {
		t.Run(test.name, func(t *testing.T) {
			result, err := host.GenerateImage(ctx, record.ID, "ark", platform.ImageRequest{Prompt: "A quiet portrait", Size: test.size, Resolution: test.resolution, OutputFormat: test.format})
			if err != nil || !bytes.Equal(result.Data, raster.Bytes()) {
				t.Fatalf("native image generation: %v", err)
			}
			input := <-requests
			if input.Model != "test-ark-image" || input.Prompt != "A quiet portrait" || input.Size != test.wantSize || input.OutputFormat != test.wantFormat {
				t.Fatalf("native options not preserved: got=%+v want size=%q format=%q", input, test.wantSize, test.wantFormat)
			}
		})
	}
	for _, test := range []struct {
		profile, resolution, format, wantError string
	}{
		{profile: "ark", format: "gif", wantError: "unsupported image format"},
		{profile: "xai", resolution: "4K", wantError: "resolution must be 1k or 2k"},
	} {
		_, err := host.GenerateImage(ctx, record.ID, test.profile, platform.ImageRequest{Prompt: "A quiet portrait", Resolution: test.resolution, OutputFormat: test.format})
		if err == nil || !strings.Contains(err.Error(), test.wantError) {
			t.Fatalf("native image validation was bypassed: %v", err)
		}
	}
	if len(requests) != 0 {
		t.Fatal("native validation failure reached the provider")
	}
}

func TestPlatformLibraryWritingUsesNativeRevisionsAndPreservesBackups(t *testing.T) {
	storyHost, scope, _ := newPlatformStateTestHost(t)
	host := platformapp.NewResources(platformHost{storyHost.app})
	input := platform.LibraryWrite{Item: platform.LibraryItem{ID: "avg-scholar", Name: "Scholar", Type: "character", Enabled: true, Content: "Original profile", Tags: []string{"avg"}}, SourceName: "A work", SourceID: "work-1"}
	first, err := host.WriteLibraryItem(context.Background(), scope.ProjectID, input)
	if err != nil {
		t.Fatal(err)
	}
	replayed, err := host.WriteLibraryItem(context.Background(), scope.ProjectID, input)
	if err != nil || replayed.UpdatedAt != first.UpdatedAt {
		t.Fatalf("identical adoption did not reuse native item: %+v %v", replayed, err)
	}
	input.Item.Content = "Revised profile"
	if _, err := host.WriteLibraryItem(context.Background(), scope.ProjectID, input); err == nil {
		t.Fatal("existing native item overwritten without revision")
	}
	input.BaseRevision = first.UpdatedAt
	updated, err := host.WriteLibraryItem(context.Background(), scope.ProjectID, input)
	if err != nil {
		t.Fatal(err)
	}
	if updated.UpdatedAt == first.UpdatedAt || updated.Content != input.Item.Content {
		t.Fatal("native revision was not updated")
	}
	_, layout, err := storyHost.app.projectRegistry.Resolve(scope.ProjectID, true)
	if err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(filepath.Join(layout.StoreRoot, "backups", "extension-library"))
	if err != nil || len(entries) != 1 {
		t.Fatalf("previous user content was not backed up: %v %v", entries, err)
	}
	backup, err := os.ReadFile(filepath.Join(layout.StoreRoot, "backups", "extension-library", entries[0].Name()))
	if err != nil {
		t.Fatal(err)
	}
	var previous booklore.Item
	if err := json.Unmarshal(backup, &previous); err != nil || previous.Content != first.Content || previous.Provenance.SourceRecordID != "work-1" {
		t.Fatalf("backup lost native content or provenance: %+v %v", previous, err)
	}
	input.Item.Content = "Stale attempt"
	if _, err := host.WriteLibraryItem(context.Background(), scope.ProjectID, input); err == nil {
		t.Fatal("stale authoring request overwrote native revision")
	}
	items, err := host.LibraryItems(context.Background(), scope.ProjectID)
	if err != nil || len(items) != 1 || items[0].Content != "Revised profile" {
		t.Fatalf("native library projection disagrees after conflict: %+v %v", items, err)
	}
}
