import { expect, test, type Page, type APIRequestContext } from '../support/fixtures'
import { createAndOpenBook, createProjectFile, createStartedStory, getStorySnapshot, getStoryBranches } from '../support/api'

function createMobileBook(request: APIRequestContext, title: string) {
  return createAndOpenBook(request, `${title} ${test.info().project.name}`)
}

async function navigate(page: Page, name: string) {
  await page.getByRole('button', { name: '导航菜单', exact: true }).click()
  const drawer = page.getByRole('dialog', { name: '导航菜单', exact: true })
  await drawer.getByRole('button', { name, exact: true }).click()
  await expect(drawer).toBeHidden()
}

async function swipe(page: Page, from: [number, number], to: [number, number]) {
  await page.evaluate(({ from, to }) => {
    const target = document.elementFromPoint(...from)!
    const touch = (point: [number, number]) => ({ identifier: 1, target, clientX: point[0], clientY: point[1] })
    // WebKit does not expose a constructible Touch. Supply complete touch lists,
    // including changedTouches used by Radix's scroll lock during drawer dismissal.
    for (const [type, point] of [['touchstart', from], ['touchmove', to], ['touchend', to]] as const) {
      const event = new Event(type, { bubbles: true, cancelable: true })
      Object.assign(event, { touches: type === 'touchend' ? [] : [touch(point)], targetTouches: type === 'touchend' ? [] : [touch(point)], changedTouches: [touch(point)] })
      target.dispatchEvent(event)
    }
  }, { from, to })
}

async function expectInsideViewport(page: Page) {
  const width = page.viewportSize()!.width
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  const shell = page.locator('[data-nova-mobile-shell="true"]')
  await expect(shell).toBeVisible()
  const bounds = await shell.boundingBox()
  expect(bounds!.width).toBeLessThanOrEqual(width)
}

async function capture(page: Page, name: string) {
  await expect(page.locator('[data-slot=loading-state]:visible')).toHaveCount(0)
  await page.screenshot({ path: test.info().outputPath(`${name}.png`), animations: 'disabled' })
}

// Full navigation at the narrowest and last compact width covers the layout
// boundaries. Intermediate portrait/landscape sizes are checked below without
// repeating all nine destination journeys and their backend setup.
for (const width of [320, 1023]) {
  test(`mobile destinations and sheets remain usable at ${width}px`, async ({ page, request }) => {
    test.setTimeout(60_000)
    await createMobileBook(request, `Mobile ${width} A long book title for navigation`)
    await page.setViewportSize({ width, height: 844 })
    await page.goto('/')
    await expect(page.locator('.nova-mobile-topbar')).toHaveCount(1)
    await expect(page.locator('.nova-mobile-nav')).toHaveCount(0)
    await page.getByRole('button', { name: '文件', exact: true }).click()
    const files = page.getByRole('dialog', { name: '项目', exact: true })
    await expect(files).toBeVisible()
    await expect(files.getByRole('button', { name: '关闭', exact: true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(files).toBeHidden()
    for (const destination of ['资料库', '创作方案', '工作台', '书籍管理', '版本管理', 'Skills', 'Agents', '自动化', '设置']) {
      await page.getByRole('button', { name: '导航菜单', exact: true }).click()
      const navigation = page.getByRole('dialog', { name: '导航菜单', exact: true })
      await expect(navigation.getByRole('button', { name: destination, exact: true })).toBeVisible()
      await expect(navigation.getByRole('button', { name: destination, exact: true }).locator('span').last()).toHaveText(destination)
      await navigation.getByRole('button', { name: destination, exact: true }).click()
      await expect(navigation).toBeHidden()
      const nav = page.getByRole('navigation', { name: '移动端工作台导航' })
      await page.getByRole('button', { name: '导航菜单', exact: true }).click()
      await expect(nav.locator('[aria-current="page"]')).toHaveCount(1)
      await expect(nav.getByRole('button', { name: destination, exact: true })).toHaveAttribute('aria-current', 'page')
      await navigation.getByRole('button', { name: '关闭', exact: true }).click()
      await expect(navigation).toBeHidden()
      await expect(page.locator('[data-slot=loading-state]:visible')).toHaveCount(0)
      await expect(page.getByRole('button', { name: /^关闭(?:设置|书籍管理|版本管理|自动化| Agents)?$/ })).toHaveCount(0)
      await expectInsideViewport(page)
    }
    for (const viewport of [{ width: 390, height: 844 }, { width: 768, height: 844 }, { width: 844, height: 390 }]) {
      await page.setViewportSize(viewport)
      await expectInsideViewport(page)
    }
    await page.setViewportSize({ width, height: 844 })
    await capture(page, `settings-${width}`)
  })
}

test('mobile Writing gives each view full space, preserves drafts, and returns from files', async ({ page, request }) => {
  const book = await createMobileBook(request, 'Mobile Writing')
  await createProjectFile(request, book.projectId, 'chapters/mobile-chapter.md', '# A mobile chapter\n\nThe station clock stopped at noon.\n')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: '文件', exact: true }).click()
  await page.getByRole('dialog', { name: '项目', exact: true }).getByRole('button', { name: /^mobile chapter/ }).click()
  await expect(page.getByRole('dialog', { name: '项目', exact: true })).toBeHidden()
  await expect(page.getByText('The station clock stopped at noon.')).toBeVisible()
  await page.getByRole('tab', { name: 'Agent', exact: true }).click()
  const composer = page.getByPlaceholder(/输入消息/)
  await composer.fill('保留这段草稿')
  await composer.press('Enter')
  await composer.pressSequentially('第二行')
  await expect(composer).toContainText('第二行')
  await page.getByRole('tab', { name: '正文', exact: true }).click()
  await expect(composer).toBeHidden()
  await expect(page.getByText('The station clock stopped at noon.')).toBeVisible()
  await page.getByRole('tab', { name: 'Agent', exact: true }).click()
  await expect(composer).toContainText('保留这段草稿')
  await expect(composer).toContainText('第二行')
  await capture(page, 'writing-agent-390')
  await page.getByRole('button', { name: '文件', exact: true }).click()
  await page.getByRole('dialog', { name: '项目', exact: true }).getByRole('button', { name: /^mobile chapter/ }).click()
  await expect(page.getByRole('tab', { name: '正文', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByText('The station clock stopped at noon.')).toBeVisible()
})

for (const theme of ['dark', 'light']) {
  test(`mobile Game supports actions, readable history, and branching in ${theme}`, async ({ page, request }) => {
    test.setTimeout(60_000)
    await createMobileBook(request, `Mobile Game ${theme}`)
    const story = await createStartedStory(request, '旧车站：一段用于验证手机长标题布局的旅行故事')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.route(/\/api\/(?:projects\/[^/]+\/)?settings$/, async (route) => {
      const response = await route.fetch()
      const settings = await response.json()
      await route.fulfill({ response, json: { ...settings, effective: { ...settings.effective, theme } } })
    })
    await page.goto('/')
    await expect(page.getByRole('tab', { name: '正文', exact: true })).toBeVisible()
    await capture(page, `writing-empty-${theme}-390`)
    await page.getByRole('button', { name: '导航菜单', exact: true }).click()
    await capture(page, `navigation-${theme}-390`)
    await page.getByRole('dialog', { name: '导航菜单', exact: true }).getByRole('button', { name: '设置', exact: true }).click()
    await expect(page.locator('.nova-mobile-topbar').getByRole('heading', { name: '设置', exact: true })).toBeVisible()
    await expect(page.getByRole('dialog', { name: '导航菜单', exact: true })).toBeHidden()
    await capture(page, `settings-${theme}-390`)
    await navigate(page, '游戏')
    const composer = page.getByPlaceholder(/你要做什么/)
    await expect(composer).toBeVisible()
    // One title bar owns navigation and story context; all other height belongs
    // to the conversation and composer, retaining 44px touch targets.
    for (const width of [320, 390]) {
      await page.setViewportSize({ width, height: 844 })
      for (const selector of ['.nova-mobile-topbar']) {
        const bounds = await page.locator(selector).boundingBox()
        expect(bounds!.height, `${selector} must leave room for the conversation`).toBeLessThanOrEqual(49)
      }
      for (const label of ['导航菜单', '选择故事线', '显示控制台']) {
        const bounds = await page.getByRole('button', { name: label, exact: true }).boundingBox()
        expect(bounds!.height).toBeGreaterThanOrEqual(44)
        expect(bounds!.width).toBeGreaterThanOrEqual(44)
      }
      await expectInsideViewport(page)
      // Fill the available composer row at each viewport, including any space
      // reserved for a classic scrollbar, while retaining the input's padding.
      await expect.poll(() => composer.evaluate(element => {
        const input = element.closest<HTMLElement>('.nova-agent-composer-textarea')!
        const body = element.closest<HTMLElement>('[data-slot="agent-composer-input"]')!
        const row = element.closest<HTMLElement>('[data-slot="agent-composer-layout"]')!
        const padding = [input, body].reduce((total, container) => {
          const style = getComputedStyle(container)
          return total + parseFloat(style.paddingLeft) + parseFloat(style.paddingRight)
        }, 0)
        const availableWidth = row.clientWidth - padding
        return Math.abs(element.getBoundingClientRect().width - availableWidth)
      })).toBeLessThan(2)
    }
    await composer.fill('推开石门')
    await composer.press('Enter')
    await composer.pressSequentially('观察灯光')
    expect((await getStorySnapshot(request, story.id)).turns).toHaveLength(1)
    await page.getByRole('button', { name: '发送', exact: true }).click()
    await expect.poll(async () => (await getStorySnapshot(request, story.id)).turns).toHaveLength(2)
    await expect(page.getByText('石门缓缓开启，暖色灯光照亮了前方的旧车站。')).toBeVisible()
    await expect(page.getByRole('button', { name: '中断 AI 执行', exact: true })).toBeHidden()
    await expect(page.locator('[data-state-panel-mode=collapsed]')).toBeVisible()
    await capture(page, `game-${theme}-390`)
    await page.getByRole('button', { name: '选择故事线', exact: true }).click()
    await page.getByRole('button', { name: '剧情轮次导航', exact: true }).click()
    const history = page.getByRole('dialog', { name: '剧情轮次导航', exact: true })
    await expect(history.getByRole('button', { name: /跳转到第/ })).toHaveCount(2)
    await history.getByRole('button', { name: '跳转到第 1 轮', exact: true }).click()
    await expect(history).toBeHidden()
    await page.getByRole('button', { name: '获取行动选择', exact: true }).click()
    await page.getByText('走进旧车站', { exact: true }).click()
    await expect(composer).toContainText('走进旧车站')
    await composer.fill('')
    await page.getByRole('button', { name: '消息操作', exact: true }).last().click()
    await page.getByRole('button', { name: '从此处创建分支', exact: true }).click()
    const dialog = page.getByRole('dialog')
    await dialog.getByLabel('剧情线名称').fill('手机支线')
    await dialog.getByRole('button', { name: '创建并切换', exact: true }).click()
    await expect.poll(async () => getStoryBranches(request, story.id)).toContainEqual(expect.objectContaining({ title: '手机支线', current: true }))
    await page.getByRole('button', { name: '显示控制台', exact: true }).click()
    const consoleSheet = page.getByRole('dialog', { name: '控制台', exact: true })
    await expect(consoleSheet).toBeVisible()
    await expect(consoleSheet).toHaveAttribute('data-side', 'right')
    await expect(consoleSheet.getByRole('button', { name: '关闭', exact: true })).toBeFocused()
    await consoleSheet.getByRole('tab', { name: /路线/ }).click()
    await capture(page, `console-${theme}-390`)
    await consoleSheet.getByRole('button', { name: '打开完整分支路线', exact: true }).click()
    await expect(consoleSheet).toBeHidden()
    await expect(page.getByRole('button', { name: '返回剧情', exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: '分支路线', exact: true })).toBeVisible()
    await expect(page.getByText('当前节点', { exact: true })).toHaveCount(1)
    await capture(page, `branches-${theme}-390`)
    await page.getByRole('button', { name: '返回剧情', exact: true }).click()
    await page.getByRole('button', { name: '显示控制台', exact: true }).click()
    await page.keyboard.press('Escape')
    await expect(consoleSheet).toBeHidden()
    await page.setViewportSize({ width: 1440, height: 1000 })
    await expect(page.getByLabel('工作台侧边栏')).toBeVisible()
    await expect(page.locator('[data-nova-mobile-shell="true"]')).toHaveCount(0)
    await expect(page.locator('.nova-story-stage-header')).toBeVisible()
    await capture(page, `desktop-game-${theme}`)
  })
}

test('the compact shell fills the PWA viewport and recovers from stale keyboard measurements', async ({ page, request }) => {
  await createMobileBook(request, 'Mobile Keyboard')
  await createStartedStory(request, 'Keyboard story')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await navigate(page, '游戏')
  const composer = page.getByPlaceholder(/你要做什么/)
  await composer.fill('草稿')
  await page.evaluate(() => {
    Object.defineProperty(window.visualViewport, 'height', { configurable: true, value: 460 })
    window.visualViewport!.dispatchEvent(new Event('resize'))
  })
  await expect(page.locator('[data-nova-mobile-shell="true"]')).toHaveCSS('height', '460px')
  await expect(page.locator('.nova-mobile-nav')).toBeHidden()
  const bounds = await page.getByRole('button', { name: '发送', exact: true }).boundingBox()
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(460)
  await expect(page.locator('.nova-story-input-float')).toHaveCSS('bottom', '0px')
  await page.evaluate(() => {
    delete (window.visualViewport as unknown as { height?: number }).height
    window.visualViewport!.dispatchEvent(new Event('resize'))
  })
  await expect.poll(async () => (await page.locator('[data-nova-mobile-shell="true"]').boundingBox())!.height).toBeCloseTo(844, 0)
  await expect(composer).toHaveText('草稿')
  // PWA resumption may report a shorter visual viewport even without a keyboard.
  await page.getByRole('button', { name: '选择故事线', exact: true }).focus()
  await page.evaluate(() => {
    Object.defineProperty(window.visualViewport, 'height', { configurable: true, value: 700 })
    Object.defineProperty(window.visualViewport, 'offsetTop', { configurable: true, value: 40 })
    window.dispatchEvent(new Event('pageshow'))
  })
  await expect.poll(async () => (await page.locator('[data-nova-mobile-shell="true"]').boundingBox())!.height).toBeCloseTo(844, 0)
  await expect(page.locator('[data-nova-mobile-shell="true"]')).toHaveCSS('top', '0px')
  const shell = await page.locator('[data-nova-mobile-shell="true"]').boundingBox()
  expect(shell!.y + shell!.height).toBeCloseTo(844, 0)
  const input = await page.locator('.nova-agent-composer').boundingBox()
  expect(844 - input!.y - input!.height).toBeLessThanOrEqual(12)
})

test('mobile writing starts from an idea or opens a file directly', async ({ page, request }) => {
  const book = await createMobileBook(request, 'Mobile Empty Writing')
  await createProjectFile(request, book.projectId, 'chapters/first-page.md', '# First page\n\nA train arrived before sunrise.\n')
  await page.setViewportSize({ width: 320, height: 568 })
  let releaseSessions!: () => void
  const sessionsReady = new Promise<void>((resolve) => { releaseSessions = resolve })
  await page.route('**/api/agent-chat/projects', async (route) => { await sessionsReady; await route.continue() })
  await page.goto('/')
  const start = page.getByRole('button', { name: '一起构思', exact: true })
  await expect(start).toBeInViewport()
  await expect(page.getByRole('button', { name: '打开文件', exact: true })).toBeInViewport()
  await start.click()
  releaseSessions()
  await expect(page.getByRole('tab', { name: 'Agent', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByPlaceholder(/输入消息/)).toContainText('请和我一起启动一本新书')
  await page.getByRole('tab', { name: '正文', exact: true }).click()
  await page.getByRole('button', { name: '打开文件', exact: true }).click()
  const files = page.getByRole('dialog', { name: '项目', exact: true })
  await files.getByRole('button', { name: /^first page/ }).click()
  await expect(files).toBeHidden()
  await expect(page.getByText('A train arrived before sunrise.', { exact: true })).toBeVisible()
})


test('mobile story setup keeps start reachable and creates a custom protagonist story', async ({ page, request }) => {
  await createMobileBook(request, 'Mobile Story Setup')
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/')
  await navigate(page, '游戏')
  await page.getByRole('button', { name: '选择故事线', exact: true }).click()
  await page.getByRole('button', { name: '新建', exact: true }).click()
  await expect(page.getByRole('heading', { name: '新故事线', exact: true })).toBeVisible()
  const advanced = page.getByRole('button', { name: '高级设置', exact: true })
  await expect(advanced).toHaveAttribute('aria-expanded', 'false')
  await advanced.click()
  await expect(advanced).toHaveAttribute('aria-expanded', 'true')
  // Match the deterministic model's fixed schema and two submitted choices.
  await page.getByRole('combobox', { name: '状态结构', exact: true }).click()
  await page.getByRole('option', { name: '固定使用模板', exact: true }).click()
  await page.getByRole('spinbutton', { name: '候选行动数', exact: true }).fill('2')
  await advanced.click()
  await page.getByRole('radio', { name: '自定义角色', exact: true }).check()
  await page.getByRole('textbox', { name: '角色名称', exact: true }).fill('林川')
  await page.getByRole('textbox', { name: '角色设定', exact: true }).fill('一位来到旧车站的旅人，寻找失散的同伴。')
  await page.getByPlaceholder('可选。写下必须保留的场景、人物处境或第一事件；留空则自动生成。').fill('夜色降临，我走到旧车站门口。')
  await capture(page, 'new-story-320')
  const start = page.getByRole('button', { name: '开始故事', exact: true })
  await expect(start).toBeEnabled()
  const bounds = await start.boundingBox()
  expect(bounds!.y + bounds!.height).toBeLessThan(740)
  await start.click()
  await expect(page.getByPlaceholder(/你要做什么/)).toBeVisible()
  await expect(page.getByRole('button', { name: '中断 AI 执行', exact: true })).toBeHidden()
  await expect(page.getByText('暮色落在旧车站外，石门后的轨道传来遥远的回声。', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('heading', { name: '新故事线', exact: true })).toBeHidden()
  await expectInsideViewport(page)
})


test('mobile navigation and pane dismissal use English consistently', async ({ page, request }) => {
  await createMobileBook(request, 'English Mobile Workspace')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.route(/\/api\/(?:projects\/[^/]+\/)?settings$/, async (route) => {
    const response = await route.fetch()
    const settings = await response.json()
    await route.fulfill({ response, json: { ...settings, effective: { ...settings.effective, language: 'en-US' } } })
  })
  await page.goto('/')
  await expect(page.locator('.nova-mobile-topbar')).toBeVisible()
  await page.getByRole('button', { name: 'Files', exact: true }).click()
  const files = page.getByRole('dialog', { name: 'Project', exact: true })
  await files.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Navigation', exact: true }).click()
  const navigation = page.getByRole('dialog', { name: 'Navigation', exact: true })
  for (const name of ['Writing', 'Game', 'Lore', 'Skills', 'Agents', 'Settings']) {
    await expect(navigation.getByRole('button', { name, exact: true })).toBeVisible()
  }
  await capture(page, 'navigation-en-390')
})


test('mobile edge gestures open the navigation and console without taking vertical scrolling', async ({ page, request }) => {
  await createMobileBook(request, 'Mobile Drawers')
  await createStartedStory(request, 'Drawer story')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await navigate(page, '游戏')
  await expect(page.getByPlaceholder(/你要做什么/)).toBeVisible()
  await swipe(page, [12, 220], [16, 330])
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await swipe(page, [12, 220], [120, 225])
  const navigation = page.getByRole('dialog', { name: '导航菜单', exact: true })
  await expect(navigation).toBeVisible()
  await expect(navigation).toHaveAttribute('data-side', 'left')
  await expect(navigation.getByRole('button', { name: '命令', exact: true })).toBeVisible()
  await expect(navigation.getByRole('button', { name: '打开消息中心', exact: true })).toBeVisible()
  await expect(navigation.getByRole('button', { name: /切换书籍/ })).toBeVisible()
  await swipe(page, [180, 24], [60, 24])
  await expect(navigation).toBeHidden()
  await page.getByPlaceholder(/你要做什么/).fill('剧情输入草稿')
  await swipe(page, [378, 220], [270, 225])
  const consoleSheet = page.getByRole('dialog', { name: '控制台', exact: true })
  await expect(consoleSheet).toBeVisible()
  await expect(consoleSheet).toHaveAttribute('data-side', 'right')
  await swipe(page, [170, 24], [290, 24])
  await expect(consoleSheet).toBeHidden()
  await expect(page.getByPlaceholder(/你要做什么/)).toHaveText('剧情输入草稿')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(page.getByPlaceholder(/你要做什么/)).toHaveText('剧情输入草稿')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByPlaceholder(/你要做什么/)).toHaveText('剧情输入草稿')
})


test('cached destinations contribute only the active title bar and preserve the game draft', async ({ page, request }) => {
  await createMobileBook(request, 'Mobile Header Ownership')
  await createStartedStory(request, 'Header story')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await navigate(page, '游戏')
  await page.getByPlaceholder(/你要做什么/).fill('保留在游戏里的草稿')
  await navigate(page, '写作')
  const header = page.locator('.nova-mobile-topbar')
  await expect(header.locator('[data-mobile-header-content]')).toHaveCount(1)
  await expect(header.getByRole('button', { name: '选择故事线', exact: true })).toHaveCount(0)
  await expect(header.getByRole('tab', { name: '正文', exact: true })).toBeVisible()
  expect((await header.getByRole('tablist').boundingBox())!.height).toBeLessThanOrEqual(48)
  await navigate(page, '设置')
  await expect(header.locator('[data-mobile-header-content]')).toHaveCount(1)
  await expect(header.getByRole('heading', { name: '设置', exact: true })).toBeVisible()
  await expect(page.locator('.nova-settings-view [data-slot="feature-page-header"]')).toBeHidden()
  await expect(page.getByRole('button', { name: '关闭设置', exact: true })).toHaveCount(0)
  const categories = header.getByRole('button', { name: '设置分类', exact: true })
  const content = page.locator('[data-nova-settings-content]')
  await expect(content.getByRole('button', { name: '设置分类', exact: true })).toHaveCount(0)
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    const bounds = (await categories.boundingBox())!
    expect(bounds.width).toBeGreaterThanOrEqual(44)
    expect(bounds.height).toBeGreaterThanOrEqual(44)
    expect(bounds.x).toBeGreaterThan(width - 72)
    await categories.focus()
    await categories.press('Enter')
    const drawer = page.getByRole('dialog', { name: '设置分类', exact: true })
    await expect(drawer).toHaveAttribute('data-side', 'right')
    await drawer.getByRole('button', { name: '路径', exact: true }).click()
    await expect(drawer).toBeHidden()
    await expect(content.getByRole('button', { name: /公共配置\s*路径/ })).toBeInViewport()
    await expect(categories).toBeFocused()
    await expect(categories).toHaveAttribute('aria-expanded', 'false')
    await categories.click()
    await expect(drawer.getByRole('button', { name: '路径', exact: true })).toHaveAttribute('aria-current', 'page')
    await drawer.getByRole('button', { name: '关闭', exact: true }).click()
    await expect(drawer).toBeHidden()
  }
  await navigate(page, '资料库')
  await expect(header.locator('[data-mobile-header-content]')).toHaveCount(1)
  await navigate(page, '游戏')
  await expect(header.locator('[data-mobile-header-content]')).toHaveCount(1)
  await expect(page.getByPlaceholder(/你要做什么/)).toHaveText('保留在游戏里的草稿')
  await page.getByRole('button', { name: '导航菜单', exact: true }).click()
  await page.getByRole('dialog', { name: '导航菜单', exact: true }).getByRole('button', { name: '命令', exact: true }).click()
  const commands = page.getByRole('dialog', { name: '命令面板', exact: true })
  await expect(page.getByRole('dialog', { name: '导航菜单', exact: true })).toBeHidden()
  await commands.getByRole('combobox').fill('搜索')
  await expect(commands.getByRole('option', { name: /打开全局搜索/ })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(commands).toBeHidden()
})

for (const destination of ['Skills', 'Agents', '资料库', '创作方案', '自动化']) {
  test(`mobile ${destination} retains its Agent draft across full-page views and primary navigation`, async ({ page, request }) => {
    await createMobileBook(request, `Resource ${destination}`)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.goto('/')
    await navigate(page, destination)
    const header = page.locator('.nova-mobile-topbar')
    await expect(header.getByRole('tablist')).toHaveCount(1)
    const directoryButton = header.getByRole('button', { name: /目录$/ })
    const bounds = (await directoryButton.boundingBox())!
    expect(bounds.x).toBeGreaterThan(318)
    await directoryButton.click()
    const directory = page.getByRole('dialog')
    await expect(directory).toHaveAttribute('data-side', 'right')
    await directory.getByRole('button', { name: '关闭', exact: true }).click()
    await expect(directory).toBeHidden()
    await header.getByRole('tab', { name: 'Agent', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    const composer = page.getByPlaceholder(/输入消息/)
    await expect(composer).toBeVisible()
    const composerBounds = (await composer.boundingBox())!
    expect(composerBounds.width).toBeGreaterThan(300)
    await composer.fill(`保留 ${destination} 的草稿`)
    const contentTab = header.getByRole('tab').first()
    await contentTab.click()
    await expect(composer).toBeHidden()
    await header.getByRole('tab', { name: 'Agent', exact: true }).click()
    await expect(composer).toHaveText(`保留 ${destination} 的草稿`)
    await navigate(page, '设置')
    await navigate(page, destination)
    await expect(composer).toHaveText(`保留 ${destination} 的草稿`)
    // Moving the retained Agent between a phone view and desktop split must preserve its input.
    await page.setViewportSize({ width: 1440, height: 1000 })
    await expect(page.locator('.nova-mobile-topbar')).toHaveCount(0)
    await page.setViewportSize({ width: 320, height: 740 })
    await expect(composer).toHaveText(`保留 ${destination} 的草稿`)
    await expectInsideViewport(page)
    await capture(page, `resource-${destination}-320`)
    if (destination === 'Skills') {
      await navigate(page, '写作')
      await page.getByRole('button', { name: '一起构思', exact: true }).click()
      await expect(page.getByPlaceholder(/输入消息/).filter({ visible: true })).toContainText('请和我一起启动一本新书')
      await navigate(page, 'Skills')
      await expect(composer).toHaveText('保留 Skills 的草稿')
    }
  })
}

test('mobile resource selections leave the directory and reveal the selected editor', async ({ page, request }) => {
  await createMobileBook(request, 'Resource directory selection')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await navigate(page, 'Skills')
  await page.getByRole('tab', { name: 'Agent', exact: true }).click()
  await page.getByRole('button', { name: 'Skills目录', exact: true }).click()
  const directory = page.getByRole('dialog', { name: 'Skills', exact: true })
  await directory.getByRole('button', { name: /\/chapter-illustration/ }).click()
  await expect(directory).toBeHidden()
  await expect(page.getByRole('tab', { name: '内容', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('heading', { name: 'Chapter Illustration', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Skills目录', exact: true }).click()
  await directory.getByRole('button', { name: '新建', exact: true }).click()
  await expect(directory).toBeHidden()
  await expect(page.getByRole('heading', { name: '新建 Skill', exact: true })).toBeVisible()
})

test('mobile workbench keeps primary and secondary conversations in retained full-page views', async ({ page, request }) => {
  const { createAgentChatSession } = await import('../support/api')
  const book = await createMobileBook(request, 'Mobile split workbench')
  const session = await createAgentChatSession(request, book.projectId, `Primary conversation ${test.info().project.name}`)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await navigate(page, '工作台')
  await page.getByRole('button', { name: '项目目录', exact: true }).click()
  const directory = page.getByRole('dialog', { name: '项目', exact: true })
  await expect(directory).toHaveAttribute('data-side', 'right')
  const project = directory.locator(`[data-slot="agent-chat-project-toggle"][data-project-id="${book.projectId}"]`)
  if (await project.getAttribute('aria-expanded') !== 'true') await project.click()
  await directory.locator('[data-slot="agent-chat-conversation-row"]').filter({ hasText: session.title }).click()
  await expect(directory).toBeHidden()
  const main = page.locator('[data-agent-chat-group="primary"]')
  const mainInput = main.getByPlaceholder(/输入消息/)
  await mainInput.fill('主会话草稿')
  await page.getByRole('button', { name: '显示右侧工作区', exact: true }).click()
  await page.getByRole('menuitem', { name: '新建对话', exact: true }).click()
  const secondary = page.locator('[data-agent-chat-group="secondary"]')
  const secondaryInput = secondary.getByPlaceholder(/输入消息/)
  await expect(secondaryInput).toBeVisible()
  await expect(mainInput).toBeHidden()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await secondaryInput.fill('辅助会话草稿')
  await page.getByRole('tab', { name: '主工作区', exact: true }).click()
  await expect(mainInput).toHaveText('主会话草稿')
  await expect(secondaryInput).toBeHidden()
  await page.getByRole('tab', { name: '辅助工作区', exact: true }).click()
  await expect(secondaryInput).toHaveText('辅助会话草稿')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await expect(mainInput).toBeVisible()
  await expect(secondaryInput).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(secondaryInput).toHaveText('辅助会话草稿')
  await page.getByRole('button', { name: '项目目录', exact: true }).click()
  await directory.locator('[data-slot="agent-chat-conversation-row"]').filter({ hasText: session.title }).click()
  await expect(directory).toBeHidden()
  await expect(mainInput).toHaveText('主会话草稿')
  await expect(page.getByRole('tab', { name: '主工作区', exact: true })).toHaveAttribute('aria-selected', 'true')
  // Native execution while a conversation is hidden is covered by the
  // concurrent-session journey in e2e/agent-chat.spec.ts. This case owns mobile
  // layout, retained drafts, and directory focus without repeating model work.
  await page.getByRole('tab', { name: '辅助工作区', exact: true }).click()
  await expect(secondaryInput).toHaveText('辅助会话草稿')
})

for (const language of ['zh-CN', 'en-US']) {
  test(`mobile automation tabs fit 320px without overlapping in ${language}`, async ({ page, request }) => {
    await createMobileBook(request, `Compact automation ${language}`)
    await page.setViewportSize({ width: 320, height: 740 })
    await page.route(/\/api\/(?:projects\/[^/]+\/)?settings$/, async (route) => {
      const response = await route.fetch()
      const settings = await response.json()
      await route.fulfill({ response, json: { ...settings, effective: { ...settings.effective, language } } })
    })
    await page.goto('/')
    const english = language === 'en-US'
    const navigationName = english ? 'Navigation' : '导航菜单'
    await page.getByRole('button', { name: navigationName, exact: true }).click()
    const navigation = page.getByRole('dialog', { name: navigationName, exact: true })
    await navigation.getByRole('button', { name: english ? 'Automations' : '自动化', exact: true }).click()
    await expect(navigation).toBeHidden()
    const header = page.locator('.nova-mobile-topbar')
    const tabs = header.getByRole('tab')
    await expect(tabs).toHaveText(english ? ['Task', 'Inbox', 'Agent'] : ['任务', '收件箱', 'Agent'])
    const buttons = header.getByRole('button')
    const left = (await buttons.first().boundingBox())!
    const right = (await buttons.last().boundingBox())!
    const tabBounds = await tabs.evaluateAll((nodes) => nodes.map((node) => {
      const rect = node.getBoundingClientRect()
      return { left: rect.left, right: rect.right, client: node.clientWidth, scroll: node.scrollWidth }
    }))
    expect(tabBounds[0].left).toBeGreaterThanOrEqual(left.x + left.width)
    expect(tabBounds.at(-1)!.right).toBeLessThanOrEqual(right.x)
    for (const bounds of tabBounds) expect(bounds.scroll).toBeLessThanOrEqual(bounds.client)
    await tabs.last().click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await capture(page, `automation-header-${language}-320`)
  })
}

test('mobile embedded Writing exposes its directory even before selecting a chapter', async ({ page, request }) => {
  const book = await createMobileBook(request, 'Embedded Writing')
  await createProjectFile(request, book.projectId, 'chapters/embedded-page.md', '# Embedded page\n\nThe nested workspace keeps its own chapter.\n')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await navigate(page, '工作台')
  await page.getByRole('button', { name: '显示右侧工作区', exact: true }).click()
  await page.getByRole('menuitem', { name: '写作', exact: true }).click()
  await page.getByRole('button', { name: '写作目录', exact: true }).click()
  const directory = page.getByRole('dialog', { name: '写作', exact: true })
  await expect(directory).toHaveAttribute('data-side', 'right')
  await directory.getByRole('button', { name: /^embedded page/ }).click()
  await expect(directory).toBeHidden()
  await expect(page.getByText('The nested workspace keeps its own chapter.', { exact: true })).toBeVisible()
  await expect(page.getByRole('tab', { name: '辅助工作区', exact: true })).toHaveAttribute('aria-selected', 'true')
})
