package interaction

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"

	agentschema "github.com/alfredxw/denova/agent/schema"
)

type InteractionKind string

const (
	InteractionAsk        InteractionKind = "ask"
	InteractionPermission InteractionKind = "permission"
)

// LocalizedText keeps host-generated permission copy bilingual without tying
// the Agent package to a presentation framework.
type LocalizedText struct {
	Chinese string `json:"zh" jsonschema:"minLength=1,maxLength=8192" jsonschema_description:"Simplified Chinese user-visible text."`
	English string `json:"en" jsonschema:"minLength=1,maxLength=8192" jsonschema_description:"English translation of the same user-visible text."`
}

// InteractionOption is model-provided Ask copy. Its visible text follows the
// current user's input language instead of duplicating localized variants.
type InteractionOption struct {
	Value       string `json:"value" jsonschema:"minLength=1,maxLength=256,pattern=^[A-Za-z0-9][A-Za-z0-9._:-]*$" jsonschema_description:"Stable option ID; other is reserved for the host-provided free-text choice."`
	Label       string `json:"label" jsonschema:"minLength=1,maxLength=4096" jsonschema_description:"Concise user-visible label in the same language as the user's current input."`
	Description string `json:"description,omitempty" jsonschema:"maxLength=4096" jsonschema_description:"Optional consequence or tradeoff in the same language as the user's current input."`
	Recommended bool   `json:"recommended,omitempty" jsonschema_description:"True for the single recommended option."`
}

type InteractionQuestion struct {
	ID            string              `json:"id" jsonschema:"minLength=1,maxLength=256,pattern=^[A-Za-z0-9][A-Za-z0-9._:-]*$" jsonschema_description:"Stable question ID used to correlate the answer."`
	Prompt        string              `json:"prompt" jsonschema:"minLength=1,maxLength=8192" jsonschema_description:"User-facing question in the same language as the user's current input."`
	Options       []InteractionOption `json:"options,omitempty" jsonschema_description:"Prefer two or three choices; use four only when every option is materially different. The host adds Other automatically."`
	Multiple      bool                `json:"multiple,omitempty" jsonschema_description:"Allow more than one listed option."`
	AllowFreeText bool                `json:"allow_free_text,omitempty" jsonschema_description:"True only for a free-text question without options."`
}

// PermissionOption remains host-localized because permission choices are
// generated by policy rather than supplied by the model-facing Ask schema.
type PermissionOption struct {
	Value       string        `json:"value"`
	Label       LocalizedText `json:"label"`
	Description LocalizedText `json:"description"`
}

type PermissionChoice string

const (
	PermissionAllowOnce PermissionChoice = "allow_once"
	PermissionRemember  PermissionChoice = "remember"
	PermissionDeny      PermissionChoice = "deny"
)

type PermissionPresentation struct {
	// ToolDefinitionHash binds this approval to the captured tool schema and
	// descriptor. It is durable authorization evidence, independent of mutable
	// model context. Older journals omit it and retain the full Definition fence.
	ToolDefinitionHash string             `json:"tool_definition_hash,omitempty"`
	Tool               string             `json:"tool"`
	CallID             string             `json:"call_id"`
	Arguments          json.RawMessage    `json:"arguments"`
	Reason             LocalizedText      `json:"reason"`
	Mode               string             `json:"mode"`
	Command            string             `json:"command,omitempty"`
	Details            string             `json:"details,omitempty"`
	Cwd                string             `json:"cwd,omitempty"`
	Risk               string             `json:"risk"`
	RuleID             string             `json:"rule_id"`
	ArgsHash           string             `json:"args_hash"`
	CanRemember        bool               `json:"can_remember,omitempty"`
	RuleMatcherVersion int                `json:"rule_matcher_version,omitempty"`
	RuleMatchKey       string             `json:"rule_match_key,omitempty"`
	RuleDisplayPattern string             `json:"rule_display_pattern,omitempty"`
	Options            []PermissionOption `json:"options"`
}

// InteractionRequest is the only host-input vocabulary. Exactly one
// of Questions or Permission is selected by Kind.
type InteractionRequest struct {
	ID         string                  `json:"id"`
	Kind       InteractionKind         `json:"kind"`
	Questions  []InteractionQuestion   `json:"questions,omitempty"`
	Permission *PermissionPresentation `json:"permission,omitempty"`
	AllowOther bool                    `json:"allow_other,omitempty"`
	// Verification is host-owned evidence for an unknown external tool effect.
	// Its stable call identity, never the question wording, controls resolution.
	Verification *ToolEffectVerification `json:"verification,omitempty"`
}

type ToolEffectVerification struct {
	ExecutionID string          `json:"execution_id"`
	Tool        string          `json:"tool"`
	Arguments   json.RawMessage `json:"arguments"`
}

type InteractionAnswer struct {
	QuestionID string   `json:"question_id" jsonschema:"minLength=1,maxLength=256" jsonschema_description:"Question ID being answered."`
	Values     []string `json:"values,omitempty" jsonschema_description:"Selected option values for a choice question."`
	Text       string   `json:"text,omitempty" jsonschema:"maxLength=65536" jsonschema_description:"User-entered answer for a free-text or Other choice."`
}

type InteractionResponse struct {
	Answers    []InteractionAnswer `json:"answers,omitempty"`
	Permission PermissionChoice    `json:"permission,omitempty"`
	Cancelled  bool                `json:"cancelled,omitempty"`
}

// InteractionResolution is validated and normalized before it reaches a Tool.
// Accepted requests and responses are journal facts; waiters remain process-local.
type InteractionResolution struct {
	Answers    []InteractionAnswer `json:"answers,omitempty"`
	Permission PermissionChoice    `json:"permission,omitempty"`
	Cancelled  bool                `json:"cancelled,omitempty"`
}

// askResolutionContract is the durable part of an Ask request. Presentation
// copy is deliberately excluded so an already-emitted Ask can still be
// answered after its model-facing text schema changes.
type askResolutionContract struct {
	ID         string
	Questions  []askResolutionQuestion
	AllowOther bool
}

type askResolutionQuestion struct {
	ID            string
	OptionValues  []string
	Multiple      bool
	AllowFreeText bool
}

type InteractionPolicy interface {
	Identity() agentschema.CapabilityIdentity
	ValidateRequest(context.Context, InteractionRequest) error
	Resolve(context.Context, InteractionRequest, InteractionResponse) (InteractionResolution, error)
}

type standardInteractionPolicy struct{}

const (
	maxInteractionRequestBytes      = 128 << 10
	maxInteractionStableIDBytes     = 256
	maxInteractionQuestionTextBytes = 8 << 10
	maxInteractionOptionTextBytes   = 4 << 10
	maxInteractionAnswerTextBytes   = 64 << 10
	maxInteractionChoiceOptions     = 4
	interactionChoiceOptionRange    = "two to four"
	reservedInteractionOtherValue   = "other"
)

var interactionStableIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:-]*$`)

func (standardInteractionPolicy) Identity() agentschema.CapabilityIdentity {
	return agentschema.CapabilityIdentity{Kind: "interaction.standard", Version: 3}
}

func (standardInteractionPolicy) ValidateRequest(_ context.Context, request InteractionRequest) error {
	if err := validateInteractionStableID("Interaction Request ID", request.ID); err != nil {
		return err
	}
	switch request.Kind {
	case InteractionAsk:
		if request.Permission != nil || len(request.Questions) < 1 || len(request.Questions) > 3 {
			return errors.New("ask Interaction requires one to three questions")
		}
		seen := make(map[string]struct{}, len(request.Questions))
		for index, question := range request.Questions {
			if err := validateInteractionQuestion(question); err != nil {
				return fmt.Errorf("Interaction question %d: %w", index, err)
			}
			if _, duplicate := seen[question.ID]; duplicate {
				return fmt.Errorf("Interaction question %q is duplicated", question.ID)
			}
			seen[question.ID] = struct{}{}
		}
		encoded, err := json.Marshal(request.Questions)
		if err != nil {
			return fmt.Errorf("encode ask Interaction questions: %w", err)
		}
		if len(encoded) > maxInteractionRequestBytes {
			return fmt.Errorf("ask Interaction question payload exceeds %d bytes", maxInteractionRequestBytes)
		}
	case InteractionPermission:
		if request.Permission == nil || len(request.Questions) != 0 || strings.TrimSpace(request.Permission.Tool) == "" ||
			strings.TrimSpace(request.Permission.CallID) == "" || !json.Valid(request.Permission.Arguments) ||
			strings.TrimSpace(request.Permission.Mode) == "" || strings.TrimSpace(request.Permission.Risk) == "" ||
			strings.TrimSpace(request.Permission.RuleID) == "" || strings.TrimSpace(request.Permission.ArgsHash) == "" {
			return errors.New("permission Interaction requires tool, call ID, and valid arguments")
		}
		if err := ValidateLocalizedText(request.Permission.Reason); err != nil {
			return fmt.Errorf("permission Interaction reason: %w", err)
		}
		if err := validatePermissionOptions(request.Permission.Options, request.Permission.CanRemember); err != nil {
			return err
		}
	default:
		return fmt.Errorf("unsupported Interaction kind %q", request.Kind)
	}
	return nil
}

func validatePermissionOptions(options []PermissionOption, canRemember bool) error {
	want := map[string]bool{
		string(PermissionAllowOnce): true,
		string(PermissionDeny):      true,
		string(PermissionRemember):  canRemember,
	}
	seen := make(map[string]bool, len(options))
	for _, option := range options {
		if !want[option.Value] || seen[option.Value] {
			return fmt.Errorf("permission Interaction has invalid option %q", option.Value)
		}
		seen[option.Value] = true
		if err := ValidateLocalizedText(option.Label); err != nil {
			return fmt.Errorf("permission option %q label: %w", option.Value, err)
		}
		if err := ValidateLocalizedText(option.Description); err != nil {
			return fmt.Errorf("permission option %q description: %w", option.Value, err)
		}
	}
	if !seen[string(PermissionAllowOnce)] || !seen[string(PermissionDeny)] ||
		canRemember != seen[string(PermissionRemember)] {
		return errors.New("permission Interaction options do not match policy choices")
	}
	return nil
}

func validateInteractionQuestion(question InteractionQuestion) error {
	if err := validateInteractionStableID("ID", question.ID); err != nil {
		return err
	}
	if strings.TrimSpace(question.Prompt) == "" {
		return errors.New("prompt is required")
	}
	if len(question.Prompt) > maxInteractionQuestionTextBytes {
		return fmt.Errorf("prompt exceeds %d bytes", maxInteractionQuestionTextBytes)
	}
	if len(question.Options) == 0 {
		if !question.AllowFreeText || question.Multiple {
			return errors.New("free-text question must allow text and cannot be multi-select")
		}
		return nil
	}
	if len(question.Options) < 2 || len(question.Options) > maxInteractionChoiceOptions {
		return errors.New("choice question requires " + interactionChoiceOptionRange + " options")
	}
	seen := make(map[string]struct{}, len(question.Options))
	recommended := 0
	for _, option := range question.Options {
		if err := validateInteractionStableID("option value", option.Value); err != nil {
			return err
		}
		if strings.EqualFold(option.Value, reservedInteractionOtherValue) {
			return fmt.Errorf("option value %q is reserved for the host-provided Other choice", option.Value)
		}
		if _, duplicate := seen[option.Value]; duplicate {
			return fmt.Errorf("option %q is duplicated", option.Value)
		}
		seen[option.Value] = struct{}{}
		if strings.TrimSpace(option.Label) == "" {
			return fmt.Errorf("option %q label is required", option.Value)
		}
		if option.Description != "" && strings.TrimSpace(option.Description) == "" {
			return fmt.Errorf("option %q description cannot be blank", option.Value)
		}
		if len(option.Label)+len(option.Description) > maxInteractionOptionTextBytes {
			return fmt.Errorf("option %q text exceeds %d bytes", option.Value, maxInteractionOptionTextBytes)
		}
		if option.Recommended {
			recommended++
		}
	}
	if recommended != 1 {
		return errors.New("choice question requires exactly one recommended option")
	}
	return nil
}

func ValidateLocalizedText(value LocalizedText) error {
	if strings.TrimSpace(value.Chinese) == "" || strings.TrimSpace(value.English) == "" {
		return errors.New("both Chinese and English text are required")
	}
	return nil
}

func validateInteractionStableID(field, value string) error {
	if value == "" || strings.TrimSpace(value) != value || len(value) > maxInteractionStableIDBytes ||
		!interactionStableIDPattern.MatchString(value) {
		return fmt.Errorf("%s must contain 1..%d bytes using letters, numbers, '.', '_', ':', or '-'", field, maxInteractionStableIDBytes)
	}
	return nil
}

func (policy standardInteractionPolicy) Resolve(ctx context.Context, request InteractionRequest, response InteractionResponse) (InteractionResolution, error) {
	if err := policy.ValidateRequest(ctx, request); err != nil {
		return InteractionResolution{}, err
	}
	if response.Cancelled {
		return InteractionResolution{Cancelled: true}, nil
	}
	switch request.Kind {
	case InteractionPermission:
		switch response.Permission {
		case PermissionAllowOnce, PermissionRemember, PermissionDeny:
			return InteractionResolution{Permission: response.Permission}, nil
		default:
			return InteractionResolution{}, fmt.Errorf("%w: permission response must allow once, remember, or deny", agentschema.ErrInvalidInteractionResponse)
		}
	case InteractionAsk:
		return resolveAskResolution(askResolutionContractFromRequest(request), response)
	default:
		return InteractionResolution{}, fmt.Errorf("unsupported Interaction kind %q", request.Kind)
	}
}

func askResolutionContractFromRequest(request InteractionRequest) askResolutionContract {
	contract := askResolutionContract{
		ID: request.ID, AllowOther: request.AllowOther,
		Questions: make([]askResolutionQuestion, 0, len(request.Questions)),
	}
	for _, question := range request.Questions {
		values := make([]string, 0, len(question.Options))
		for _, option := range question.Options {
			values = append(values, option.Value)
		}
		contract.Questions = append(contract.Questions, askResolutionQuestion{
			ID: question.ID, OptionValues: values,
			Multiple: question.Multiple, AllowFreeText: question.AllowFreeText,
		})
	}
	return contract
}

func decodePersistedAskResolutionContract(encoded json.RawMessage) (askResolutionContract, error) {
	if len(encoded) > maxInteractionRequestBytes+(4<<10) {
		return askResolutionContract{}, fmt.Errorf("persisted ask Interaction exceeds %d bytes", maxInteractionRequestBytes+(4<<10))
	}
	var stored struct {
		ID         string          `json:"id"`
		Kind       InteractionKind `json:"kind"`
		Permission json.RawMessage `json:"permission,omitempty"`
		Questions  []struct {
			ID            string `json:"id"`
			Multiple      bool   `json:"multiple,omitempty"`
			AllowFreeText bool   `json:"allow_free_text,omitempty"`
			Options       []struct {
				Value string `json:"value"`
			} `json:"options,omitempty"`
		} `json:"questions"`
		AllowOther bool `json:"allow_other,omitempty"`
	}
	if err := json.Unmarshal(encoded, &stored); err != nil {
		return askResolutionContract{}, fmt.Errorf("decode persisted Ask resolution contract: %w", err)
	}
	if stored.Kind != InteractionAsk {
		return askResolutionContract{}, fmt.Errorf("persisted Interaction kind %q is not Ask", stored.Kind)
	}
	if len(stored.Permission) != 0 && string(stored.Permission) != "null" {
		return askResolutionContract{}, errors.New("persisted Ask Interaction contains a Permission presentation")
	}
	contract := askResolutionContract{
		ID: stored.ID, AllowOther: stored.AllowOther,
		Questions: make([]askResolutionQuestion, 0, len(stored.Questions)),
	}
	for _, question := range stored.Questions {
		values := make([]string, 0, len(question.Options))
		for _, option := range question.Options {
			values = append(values, option.Value)
		}
		contract.Questions = append(contract.Questions, askResolutionQuestion{
			ID: question.ID, OptionValues: values,
			Multiple: question.Multiple, AllowFreeText: question.AllowFreeText,
		})
	}
	if err := validateAskResolutionContract(contract); err != nil {
		return askResolutionContract{}, err
	}
	return contract, nil
}

func validateAskResolutionContract(contract askResolutionContract) error {
	if err := validateInteractionStableID("Interaction Request ID", contract.ID); err != nil {
		return err
	}
	if len(contract.Questions) < 1 || len(contract.Questions) > 3 {
		return errors.New("persisted Ask Interaction requires one to three questions")
	}
	seenQuestions := make(map[string]struct{}, len(contract.Questions))
	for index, question := range contract.Questions {
		if err := validateInteractionStableID("ID", question.ID); err != nil {
			return fmt.Errorf("persisted Ask question %d: %w", index, err)
		}
		if _, duplicate := seenQuestions[question.ID]; duplicate {
			return fmt.Errorf("persisted Ask question %q is duplicated", question.ID)
		}
		seenQuestions[question.ID] = struct{}{}
		if len(question.OptionValues) == 0 {
			if !question.AllowFreeText || question.Multiple {
				return fmt.Errorf("persisted free-text question %q must allow text and cannot be multi-select", question.ID)
			}
			continue
		}
		if len(question.OptionValues) < 2 || len(question.OptionValues) > maxInteractionChoiceOptions {
			return fmt.Errorf("persisted choice question %q requires %s options", question.ID, interactionChoiceOptionRange)
		}
		seenOptions := make(map[string]struct{}, len(question.OptionValues))
		for _, value := range question.OptionValues {
			if err := validateInteractionStableID("option value", value); err != nil {
				return fmt.Errorf("persisted Ask question %q: %w", question.ID, err)
			}
			if strings.EqualFold(value, reservedInteractionOtherValue) {
				return fmt.Errorf("persisted Ask option value %q is reserved", value)
			}
			if _, duplicate := seenOptions[value]; duplicate {
				return fmt.Errorf("persisted Ask question %q duplicates option %q", question.ID, value)
			}
			seenOptions[value] = struct{}{}
		}
	}
	return nil
}

func ResolvePersistedStandardAsk(encoded json.RawMessage, response InteractionResponse) (InteractionResolution, error) {
	contract, err := decodePersistedAskResolutionContract(encoded)
	if err != nil {
		return InteractionResolution{}, err
	}
	if response.Cancelled {
		return InteractionResolution{Cancelled: true}, nil
	}
	return resolveAskResolution(contract, response)
}

func resolveAskResolution(contract askResolutionContract, response InteractionResponse) (resolution InteractionResolution, err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("%w: %w", agentschema.ErrInvalidInteractionResponse, err)
		}
	}()
	questions := make(map[string]askResolutionQuestion, len(contract.Questions))
	for _, question := range contract.Questions {
		questions[question.ID] = question
	}
	answers := make(map[string]InteractionAnswer, len(response.Answers))
	for _, answer := range response.Answers {
		if len(answer.Text) > maxInteractionAnswerTextBytes {
			return InteractionResolution{}, fmt.Errorf("custom answer for %q exceeds %d bytes", answer.QuestionID, maxInteractionAnswerTextBytes)
		}
		question, exists := questions[answer.QuestionID]
		if !exists {
			return InteractionResolution{}, fmt.Errorf("answer targets unknown question %q", answer.QuestionID)
		}
		if _, duplicate := answers[answer.QuestionID]; duplicate {
			return InteractionResolution{}, fmt.Errorf("question %q has multiple answers", answer.QuestionID)
		}
		allowed := make(map[string]struct{}, len(question.OptionValues))
		for _, value := range question.OptionValues {
			allowed[value] = struct{}{}
		}
		if !question.Multiple && len(answer.Values) > 1 {
			return InteractionResolution{}, fmt.Errorf("question %q accepts one option", answer.QuestionID)
		}
		seen := make(map[string]struct{}, len(answer.Values))
		for _, value := range answer.Values {
			if _, ok := allowed[value]; !ok {
				return InteractionResolution{}, fmt.Errorf("question %q received unknown option %q", answer.QuestionID, value)
			}
			if _, duplicate := seen[value]; duplicate {
				return InteractionResolution{}, fmt.Errorf("question %q repeats option %q", answer.QuestionID, value)
			}
			seen[value] = struct{}{}
		}
		answer.Text = strings.TrimSpace(answer.Text)
		if len(question.OptionValues) == 0 {
			if len(answer.Values) != 0 || answer.Text == "" {
				return InteractionResolution{}, fmt.Errorf("free-text question %q requires text and no option", answer.QuestionID)
			}
		} else if answer.Text != "" {
			if !contract.AllowOther {
				return InteractionResolution{}, fmt.Errorf("question %q does not accept free text", answer.QuestionID)
			}
			if len(answer.Values) != 0 && !question.Multiple {
				return InteractionResolution{}, fmt.Errorf("question %q cannot combine Other with a selected option", answer.QuestionID)
			}
		}
		if len(answer.Values) == 0 && strings.TrimSpace(answer.Text) == "" {
			return InteractionResolution{}, fmt.Errorf("question %q has an empty answer", answer.QuestionID)
		}
		answer.Values = append([]string(nil), answer.Values...)
		answers[answer.QuestionID] = answer
	}
	if len(answers) != len(contract.Questions) {
		return InteractionResolution{}, errors.New("every Interaction question requires an answer")
	}
	ordered := make([]InteractionAnswer, 0, len(contract.Questions))
	for _, question := range contract.Questions {
		ordered = append(ordered, answers[question.ID])
	}
	return InteractionResolution{Answers: ordered}, nil
}

type interactionClient interface {
	Request(context.Context, InteractionRequest) (InteractionResolution, error)
}

type interactionContextKey struct{}

func ContextWithInteractionClient(ctx context.Context, client interactionClient) context.Context {
	return context.WithValue(ctx, interactionContextKey{}, client)
}

// RequestInteraction asks through the current Run. It is available to
// custom tools and returns an error when called outside Agent execution.
func RequestInteraction(ctx context.Context, request InteractionRequest) (InteractionResolution, error) {
	if ctx == nil {
		return InteractionResolution{}, agentschema.ErrCapabilityUnsupported
	}
	client, ok := ctx.Value(interactionContextKey{}).(interactionClient)
	if !ok || client == nil {
		return InteractionResolution{}, agentschema.ErrCapabilityUnsupported
	}
	return client.Request(ctx, request)
}

func DecodeInteractionResolution(encoded json.RawMessage) (InteractionResolution, error) {
	var resolution InteractionResolution
	if err := json.Unmarshal(encoded, &resolution); err != nil {
		return InteractionResolution{}, fmt.Errorf("decode Interaction resolution: %w", err)
	}
	return resolution, nil
}

func EffectiveInteractionPolicy(policy InteractionPolicy) InteractionPolicy {
	if policy == nil {
		return standardInteractionPolicy{}
	}
	return policy
}

func IsStandardInteractionPolicy(policy InteractionPolicy) bool {
	_, ok := policy.(standardInteractionPolicy)
	return ok
}

// StandardInteraction returns the built-in validation and normalization
// policy for Ask and permission interactions.
func StandardInteraction() InteractionPolicy { return standardInteractionPolicy{} }
