import { expect, test } from '../support/fixtures'
import { createAndOpenBook } from '../support/api'
import type { LoreItem } from '../../src/lib/api'

for (const theme of ['dark', 'light']) {
  test(`inserts and follows name references without losing drafts in ${theme}`, async ({ page, request }, testInfo) => {
    const book = await createAndOpenBook(request, `Lore references ${theme}`)
    const url = `/api/projects/${book.projectId}/book/lore/items`
    const items = async (): Promise<LoreItem[]> => (await (await request.get(url)).json()).items
    const settings = await (await request.get('/api/settings')).json()
    await request.patch('/api/settings', { data: { layer: 'user', base_revision: settings.revisions.user, changes: { theme, language: 'zh-CN' } } })
    const longName = '长名称LongName'.repeat(12)
    for (const item of [
      { id: 'hero', name: '沈凝', content: 'Draft before referencing.', enabled: true },
      { id: 'tower', name: '白塔议会', content: 'Council details. Meets [[沈凝]].', enabled: true },
      { id: 'station', name: longName, content: '', enabled: false },
    ]) {
      const response = await request.post(url, { data: { type: 'world', tags: [], ...item } })
      expect(response.ok(), await response.text()).toBe(true)
    }
    await page.setViewportSize({ width: 1600, height: 1000 })
    await page.goto('/')
    const sidebar = page.getByLabel('工作台侧边栏')
    await sidebar.getByRole('button', { name: '资料库', exact: true }).click()
    await page.getByTestId('lore-card-hero').click()
    const body = page.getByRole('textbox', { name: '正文', exact: true })
    await expect(body).toBeVisible()
    await body.press('Control+End')
    await page.keyboard.insertText(' @白塔')
    const candidate = page.getByRole('option', { name: /^@白塔议会/ })
    await expect(candidate).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`reference-${theme}-picker.png`) })
    await page.keyboard.press('Enter')
    await expect(candidate).toHaveCount(0)
    const link = body.getByRole('button', { name: '查看资料：白塔议会', exact: true })
    await expect(link).toHaveText('白塔议会')
    await body.press(process.platform === 'darwin' ? 'Meta+S' : 'Control+S')
    await expect.poll(async () => (await items()).find(item => item.id === 'hero')?.content).toContain('[[白塔议会]]')

    // A dismissed @ remains literal, including during IME composition.
    await body.press('Control+End')
    await page.keyboard.insertText(' @No match')
    await expect(page.getByText('没有匹配的资料', { exact: true })).toBeVisible()
    await body.dispatchEvent('compositionstart')
    await body.press('Enter', { noWaitAfter: true })
    await body.dispatchEvent('compositionend')
    await page.keyboard.press('Escape')
    await body.press(process.platform === 'darwin' ? 'Meta+S' : 'Control+S')
    await expect.poll(async () => (await items()).find(item => item.id === 'hero')?.content).toContain('@No match')

    await page.getByRole('textbox', { name: '简介', exact: true }).fill('Keep this draft when opening a reference.')
    await link.click()
    const preview = page.getByTestId('lore-reference-preview')
    await expect(preview.getByRole('heading', { name: '白塔议会', exact: true })).toBeVisible()
    await expect(preview).toContainText('Council details.')
    await preview.getByRole('button', { name: '查看资料：沈凝', exact: true }).click()
    await expect(preview).toContainText('Draft before referencing.')
    await preview.getByRole('button', { name: '返回上一条资料', exact: true }).click()
    await expect(preview.getByRole('heading', { name: '白塔议会', exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`reference-${theme}-preview-wide.png`) })
    await preview.getByRole('button', { name: '打开资料项', exact: true }).click()
    await expect(preview).toHaveCount(0)
    await expect(page.getByRole('textbox', { name: '名称', exact: true })).toHaveValue('白塔议会')
    expect((await items()).find(item => item.id === 'hero')?.brief_description).toBe('Keep this draft when opening a reference.')
    await body.getByRole('button', { name: '查看资料：沈凝', exact: true }).click()
    await preview.getByRole('button', { name: '打开资料项', exact: true }).click()
    await expect(preview).toHaveCount(0)
    await expect(body).toContainText('@No match')
    await page.getByTestId('lore-references').getByRole('button', { name: '引用了 1 项 · 被 1 项引用' }).click()
    await expect(page.getByTestId('lore-references').getByRole('button', { name: '白塔议会', exact: true })).toHaveCount(2)

    await page.getByRole('button', { name: 'Raw', exact: true }).click()
    await expect(body).toContainText('[[白塔议会]]')
    await body.press('Control+End')
    await page.keyboard.insertText(' @白塔')
    await page.getByRole('option', { name: /^@白塔议会/ }).click()
    await expect(body).toContainText('[[白塔议会]]')
    await body.press(process.platform === 'darwin' ? 'Meta+A' : 'Control+A')
    await page.keyboard.insertText(`Updated draft. [[白塔议会]] [[Missing]] [[${longName}]]\n\n\`[[Code]]\` and \\[[Literal]].`)
    await expect(body).toContainText('Updated draft.')
    await body.press(process.platform === 'darwin' ? 'Meta+S' : 'Control+S')
    await expect.poll(async () => (await items()).find(item => item.id === 'hero')?.content).toContain('Updated draft.')
    await page.getByRole('button', { name: '富文本', exact: true }).click()
    await expect(body.locator('[data-lore-reference]')).toHaveCount(3)
    await expect(body.getByRole('button', { name: /^资料不存在：Missing/ })).toHaveAttribute('data-reference-missing', 'true')
    await body.getByRole('button', { name: /^资料不存在：Missing/ }).click()
    await expect(preview.getByRole('status')).toContainText('资料不存在：Missing')
    await expect(preview.getByRole('button', { name: '打开资料项', exact: true })).toHaveCount(0)
    await preview.getByRole('button', { name: '关闭', exact: true }).click()
    await page.setViewportSize({ width: 390, height: 844 })
    await body.getByRole('button', { name: `查看资料：${longName}（已停用）`, exact: true }).click()
    await expect(preview).toContainText('此资料暂无正文。')
    await expect(preview).toContainText('已停用')
    expect(await preview.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await page.screenshot({ animations: 'disabled', path: testInfo.outputPath(`reference-${theme}-preview-narrow.png`) })
    await preview.getByRole('button', { name: '打开资料项', exact: true }).click()
    await expect(preview).toHaveCount(0)
    await expect(page.getByRole('textbox', { name: '名称', exact: true })).toHaveValue(longName)

    // Renaming preserves prose and exposes the unresolved name, even after reload.
    await page.setViewportSize({ width: 1920, height: 1080 })
    await page.getByRole('button', { name: '返回资料总览', exact: true }).click()
    await page.getByTestId('lore-card-tower').click()
    await expect(page.getByRole('note')).toContainText('改名后需同步修改引用')
    await page.getByRole('textbox', { name: '名称', exact: true }).fill('新议会')
    await body.press(process.platform === 'darwin' ? 'Meta+S' : 'Control+S')
    await expect.poll(async () => (await items()).find(item => item.id === 'tower')?.name).toBe('新议会')
    await page.reload()
    await page.getByTestId('lore-card-hero').click()
    await expect(body.getByRole('button', { name: /^资料不存在：白塔议会/ })).toHaveAttribute('data-reference-missing', 'true')
    expect((await items()).find(item => item.id === 'hero')?.content).toContain('[[白塔议会]]')

    await page.setViewportSize({ width: 1920, height: 1080 })
    await sidebar.getByRole('button', { name: '游戏', exact: true }).click()
    await sidebar.getByRole('button', { name: '资料库', exact: true }).click()
    await expect(page.getByText('输入 @ 引用其他资料', { exact: true })).toBeVisible()
    await body.getByRole('button', { name: `查看资料：${longName}（已停用）`, exact: true }).click()
    await preview.getByRole('button', { name: '打开资料项', exact: true }).click()
    await expect(preview).toHaveCount(0)
    await expect(page.getByRole('textbox', { name: '名称', exact: true })).toHaveValue(longName)
    await sidebar.getByRole('button', { name: '写作', exact: true }).click()
    await page.getByTestId('book-settings-header-frame').getByRole('button', { name: '设定', exact: true }).click()
    const workspace = page.getByRole('region', { name: '作品设定', exact: true })
    await workspace.getByRole('button', { name: /^沈凝/ }).click()
    const writingBody = workspace.getByRole('textbox', { name: '编辑设定：沈凝', exact: true })
    await expect(writingBody).toBeVisible()
    await writingBody.press('Control+End')
    await page.keyboard.insertText(' @新议')
    await page.getByRole('option', { name: /^@新议会/ }).click()
    await writingBody.getByRole('button', { name: '查看资料：新议会', exact: true }).click()
    await preview.getByRole('button', { name: '打开资料项', exact: true }).click()
    await expect(preview).toHaveCount(0)
    await expect(workspace.getByRole('textbox', { name: '编辑设定：新议会', exact: true })).toContainText('Council details.')
    expect((await items()).find(item => item.id === 'hero')?.content).toContain('[[新议会]]')
    if (theme === 'light') {
      const settings = await (await request.get('/api/settings')).json()
      await request.patch('/api/settings', { data: { layer: 'user', base_revision: settings.revisions.user, changes: { language: 'en-US' } } })
      await page.reload()
      await page.getByLabel('Workbench sidebar').getByRole('button', { name: 'Lore', exact: true }).click()
      await page.getByRole('button', { name: '沈凝', exact: true }).filter({ visible: true }).click()
      const library = page.getByTestId('nova-setting-directory-layout')
      await expect(library.getByText('Type @ to reference another entry', { exact: true })).toBeVisible()
      await library.getByRole('button', { name: 'View Lore: 新议会', exact: true }).click()
      await expect(preview).toContainText('Read-only preview. Close to continue editing the original entry.')
      await page.screenshot({ animations: 'disabled', path: testInfo.outputPath('reference-english-preview.png') })
      await preview.getByRole('button', { name: 'Open entry', exact: true }).click()
      await expect(preview).toHaveCount(0)
      await expect(page.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('新议会')
    }
  })
}
