import { expect, test } from '../support/fixtures'
import { createAndOpenBook } from '../support/api'
import type { LoreItem } from '../../src/lib/api'

for (const theme of ['dark', 'light']) {
  test(`edits direct Lore injection with automatic groups and live preview in ${theme}`, async ({ page, request, browserDiagnostics }, testInfo) => {
    const book = await createAndOpenBook(request, `Lore index ${theme}`)
    const base = `/api/projects/${book.projectId}/book/lore`
    const snapshot = async () => (await (await request.get(`${base}/index`)).json())
    const entries = async (): Promise<LoreItem[]> => (await (await request.get(`${base}/items`)).json()).items
    const settings = await (await request.get('/api/settings')).json()
    await request.patch('/api/settings', { data: { layer: 'user', base_revision: settings.revisions.user, changes: { theme, language: 'zh-CN', motion_intensity: 'system' } } })
    await page.emulateMedia({ reducedMotion: theme === 'dark' ? 'no-preference' : 'reduce' })
    await page.setViewportSize({ width: 1680, height: 1000 })
    await page.goto('/')
    const sidebar = page.getByLabel('工作台侧边栏')
    await sidebar.getByRole('button', { name: '资料库', exact: true }).click()
    await page.getByTestId('lore-library').getByRole('button', { name: '更多', exact: true }).click()
    await page.getByRole('menuitem', { name: '资料索引', exact: true }).click()
    const doc = page.getByTestId('lore-index-document')
    const editor = doc.getByTestId('lore-index-editor')
    const preview = doc.getByTestId('lore-index-preview')
    const auto = doc.getByTestId('lore-index-auto-group')
    const tokenEstimate = doc.getByTestId('lore-index-token-estimate')
    const previewToolbar = doc.getByTestId('lore-index-live-preview').locator('header')
    const indexToolbar = page.locator('[data-slot="feature-page-header"]').filter({ has: page.getByRole('heading', { name: /^(资料索引|Lore index)$/ }) })
    await expect(preview).toBeVisible()
    await expect(page.getByRole('heading', { name: '资料索引', exact: true })).toHaveCount(1)
    expect((await indexToolbar.boundingBox())!.height).toBeLessThan(50)
    await expect(indexToolbar.getByRole('status', { name: '所有更改均已保存', exact: true })).toBeVisible()
    expect((await doc.boundingBox())!.y).toBeCloseTo((await indexToolbar.boundingBox())!.y + (await indexToolbar.boundingBox())!.height, 0)
    expect((await previewToolbar.boundingBox())!.height).toBeLessThan(50)
    await expect(doc.getByText('还没有启用资料', { exact: true })).toBeVisible()
    await expect(doc.getByTestId('lore-index-live-preview')).toHaveAttribute('aria-busy', 'false')
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-empty.png`) })
    const resize = doc.getByRole('separator', { name: '调整实时预览宽度', exact: true })
    const previewPane = doc.locator('#lore-index-preview-pane')
    const initialWidth = (await previewPane.boundingBox())!.width
    const handle = (await resize.boundingBox())!
    await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2)
    await page.mouse.down()
    await page.mouse.move(handle.x + 100, handle.y + handle.height / 2, { steps: 10 })
    await page.mouse.up()
    await expect.poll(async () => (await previewPane.boundingBox())!.width).toBeLessThan(initialWidth - 50)
    const draggedWidth = (await previewPane.boundingBox())!.width
    await resize.press('ArrowLeft')
    await expect.poll(async () => (await previewPane.boundingBox())!.width).toBeCloseTo(draggedWidth + (await doc.boundingBox())!.width * 0.05, 0)
    const preferredWidth = (await previewPane.boundingBox())!.width
    await indexToolbar.getByRole('button', { name: '收起实时预览', exact: true }).click()
    await expect(preview).toBeHidden()
    await expect(resize).toBeHidden()
    await expect.poll(async () => (await editor.boundingBox())!.width).toBeGreaterThan((await doc.boundingBox())!.width - 2)
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-collapsed.png`) })
    await page.setViewportSize({ width: 390, height: 844 })
    await indexToolbar.getByRole('button', { name: '展开实时预览', exact: true }).click()
    await expect(preview).toBeVisible()
    await indexToolbar.getByRole('button', { name: '收起实时预览', exact: true }).click()
    await page.setViewportSize({ width: 1680, height: 1000 })
    await expect(preview).toBeHidden()
    await indexToolbar.getByRole('button', { name: '展开实时预览', exact: true }).click()
    await expect(preview).toBeVisible()
    await expect.poll(async () => (await previewPane.boundingBox())!.width).toBeCloseTo(preferredWidth, 0)
    for (const [name, type, load_mode, content] of [
      ['世界法则', 'world', 'resident', 'RESIDENT CANON BODY'],
      ['港口人物', 'character', 'auto', 'CAPTAIN FULL BODY'],
      ['旧码头', 'location', 'manual', 'DOCKS FULL BODY'],
    ]) {
      const response = await request.post(`${base}/items`, { data: { id: `opaque-storage-${type}-${load_mode}`, name, type, content, brief_description: type === 'location' ? '' : `摘要 ${name} ${'长简介LongUnbrokenDescription'.repeat(20)}`, tags: ['Hidden index tag'], keywords: type === 'character' ? ['港务官员'] : [], load_mode } })
      expect(response.ok(), await response.text()).toBe(true)
    }
    const ids = (await entries()).map(item => item.id)
    await expect(preview).toContainText('RESIDENT CANON BODY')
    await expect(preview).toContainText('港口人物')
    await expect(preview).toContainText('旧码头')
    await expect(preview).toContainText('世界法则 (Worldbuilding / important / full)')
    await expect(preview).toContainText('港口人物 (Character / important / name)')
    await expect(preview).toContainText('旧码头 (Location / important / name)')
    await expect(preview).not.toContainText('CAPTAIN FULL BODY')
    await expect(preview).not.toContainText('Hidden index tag')
    for (const id of ids) await expect(preview).not.toContainText(id)
    await expect(auto).toHaveCount(3)
    const initialPreview = await (await request.post(`${base}/index/preview`, { data: (await snapshot()).guide })).json()
    expect(initialPreview.token_estimate).toBeGreaterThan(0)
    await expect(tokenEstimate).toHaveText(`约 ${initialPreview.token_estimate.toLocaleString('zh-CN')} tokens`)
    await expect(doc.getByTestId('lore-index-live-preview').locator('header')).not.toContainText('KiB')
    expect((await preview.boundingBox())!.x).toBeGreaterThan((await editor.boundingBox())!.x)
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-automatic.png`) })
    const characters = auto.filter({ hasText: '角色 · 按需' })
    const trigger = characters.locator('[data-slot="collapsible-trigger"]')
    expect((await trigger.boundingBox())!.height).toBe((await characters.getByRole('group').boundingBox())!.height)
    // Exercise both transition directions with full and reduced motion.
    expect(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(theme === 'light')
    for (const expanded of [true, false]) {
      const heights = await characters.evaluate(async group => {
        const content = group.querySelector<HTMLElement>('[data-slot="collapsible-content"]')!
        const samples = [content.getBoundingClientRect().height]
        group.querySelector<HTMLButtonElement>('[data-slot="collapsible-trigger"]')!.click()
        const start = performance.now()
        await new Promise<void>(resolve => {
          const sample = () => {
            samples.push(content.getBoundingClientRect().height)
            if (performance.now() - start < 300) requestAnimationFrame(sample)
            else resolve()
          }
          requestAnimationFrame(sample)
        })
        return samples
      })
      await expect(trigger).toHaveAttribute('aria-expanded', String(expanded))
      if (expanded) {
        const card = characters.getByTestId('lore-card-opaque-storage-character-auto')
        await expect(card.locator('[data-slot="card-description"]')).toContainText('摘要 港口人物')
        await expect(card.getByText('Hidden index tag', { exact: true })).toHaveCount(0)
        expect(await card.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
        await page.screenshot({ path: testInfo.outputPath(`index-${theme}-automatic-cards.png`) })
      }
      expect(heights.at(-1)! > 0).toBe(expanded)
      const min = Math.min(heights[0], heights.at(-1)!)
      const max = Math.max(heights[0], heights.at(-1)!)
      expect(heights.some(height => height > min + 0.5 && height < max - 0.5), `Disclosure heights: ${heights.join(', ')}`).toBe(theme === 'dark')
    }
    await characters.getByRole('radio', { name: '简介', exact: true }).click()
    await expect(preview).toContainText('摘要 港口人物')
    await expect(preview).toContainText('港口人物 (Character / important / brief)')
    await expect.poll(async () => (await snapshot()).guide.automatic_details?.['auto:character']).toBe('brief')
    await doc.getByRole('button', { name: '添加分组', exact: true }).click()
    const section = doc.getByTestId('lore-index-section')
    await section.getByRole('button', { name: '编辑分组：分组 1', exact: true }).click()
    await page.getByRole('textbox', { name: '分组标题', exact: true }).fill('港城设定')
    await page.getByRole('textbox', { name: '导航说明', exact: true }).fill('探索港口人物与世界规则。')
    await page.getByRole('button', { name: '完成', exact: true }).click()
    await section.getByRole('button', { name: '补充说明', exact: true }).click()
    await section.getByRole('textbox', { name: '分组说明：港城设定', exact: true }).fill('DIRECT GROUP NOTES')
    await expect(preview).toContainText('DIRECT GROUP NOTES')
    // Search changes preserve selection; nothing is saved before submission.
    await section.getByRole('button', { name: '关联资料', exact: true }).click()
    const picker = page.getByRole('dialog', { name: '关联资料', exact: true })
    const search = picker.getByRole('textbox')
    await picker.getByRole('checkbox', { name: '旧码头', exact: true }).check()
    await picker.getByRole('button', { name: '取消', exact: true }).click()
    await section.getByRole('button', { name: '关联资料', exact: true }).click()
    await expect(picker.getByText('已选 0 项', { exact: true })).toBeVisible()
    await search.fill('港务官员')
    await picker.getByRole('checkbox', { name: '港口人物', exact: true }).check()
    await search.fill('世界')
    await search.press('Tab')
    await page.keyboard.press('Space')
    await expect(picker.getByText('已选 2 项', { exact: true })).toBeVisible()
    await search.fill('no matching entry')
    await expect(picker.getByText('已选 2 项', { exact: true })).toBeVisible()
    await search.fill('')
    for (const name of ['港口人物', '世界法则']) await expect(picker.getByRole('checkbox', { name, exact: true })).toBeChecked()
    expect((await entries()).every(item => !item.index_memberships?.length)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-multiselect.png`) })
    await page.setViewportSize({ width: 320, height: 844 })
    await section.getByRole('button', { name: '关联资料', exact: true }).scrollIntoViewIfNeeded()
    await expect(picker.getByRole('button', { name: '关联所选', exact: true })).toBeInViewport()
    await expect.poll(async () => (await picker.boundingBox())!.x).toBeGreaterThanOrEqual(0)
    await expect.poll(async () => {
      const box = (await picker.boundingBox())!
      return box.x + box.width
    }).toBeLessThanOrEqual(320)
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-multiselect-320.png`) })
    await page.setViewportSize({ width: 1680, height: 1000 })
    if (theme === 'dark') {
      browserDiagnostics.allow(/console\.error:.*409 \(Conflict\).*opaque-storage-world-resident/)
      browserDiagnostics.allow(/console\.error: \[lore-index\] item update failed/)
      await page.route(`**${base}/items/opaque-storage-world-resident`, async route => {
        await route.fulfill({ status: 409, json: { error: 'Test revision conflict', code: 'api.resource.revisionConflict' } })
      }, { times: 1 })
    }
    await picker.getByRole('button', { name: '关联所选', exact: true }).click()
    if (theme === 'dark') {
      await expect(picker.getByText('已选 1 项', { exact: true })).toBeVisible()
      await expect(picker.getByRole('checkbox', { name: '港口人物', exact: true })).toHaveCount(0)
      await expect(picker.getByRole('checkbox', { name: '世界法则', exact: true })).toBeChecked()
      await picker.getByRole('button', { name: '关联所选', exact: true }).click()
    }
    await expect(picker).toBeHidden()
    // Name-only groups publish their member names without a group-reading hop.
    for (const name of ['港口人物', '世界法则']) {
      await expect.poll(async () => (await entries()).find(i => i.name === name)?.index_memberships?.length).toBe(1)
    }
    await expect(auto).toHaveCount(1)
    await expect(preview).toContainText('港口人物')
    await expect(preview).not.toContainText('摘要 港口人物')
    await expect(preview).not.toContainText('RESIDENT CANON BODY')
    const defaultDetail = section.getByRole('group', { name: '组内默认注入', exact: true })
    await defaultDetail.getByRole('radio', { name: '名称', exact: true }).press('ArrowRight')
    await expect(defaultDetail.getByRole('radio', { name: '简介', exact: true })).toBeFocused()
    await defaultDetail.getByRole('radio', { name: '简介', exact: true }).press('Space')
    await expect(defaultDetail.getByRole('radio', { name: '简介', exact: true })).toBeChecked()
    await defaultDetail.getByRole('radio', { name: '全文', exact: true }).click()
    await defaultDetail.getByRole('radio', { name: '全文', exact: true }).click()
    await expect(defaultDetail.getByRole('radio', { name: '全文', exact: true })).toBeChecked()
    await expect(preview).toContainText('CAPTAIN FULL BODY')
    await expect(preview).toContainText('RESIDENT CANON BODY')
    await expect(preview).toContainText('港口人物 (Character / important / full)')
    await expect(preview).not.toContainText('摘要 港口人物')
    await expect.poll(async () => (await snapshot()).guide.groups[0].default_detail).toBe('full')
    const fullPreview = await (await request.post(`${base}/index/preview`, { data: (await snapshot()).guide })).json()
    await expect(tokenEstimate).toHaveText(`约 ${fullPreview.token_estimate.toLocaleString('zh-CN')} tokens`)
    const characterCard = section.getByTestId('lore-card-opaque-storage-character-auto')
    await expect(characterCard.locator('[data-slot="card-description"]')).toContainText('摘要 港口人物')
    await expect(characterCard.getByText('Hidden index tag', { exact: true })).toHaveCount(0)
    const options = characterCard.getByRole('button', { name: '加载选项：港口人物', exact: true })
    await options.click()
    const itemDetail = page.getByRole('dialog', { name: '加载选项：港口人物', exact: true }).getByRole('combobox', { name: '当前分组展示', exact: true })
    await itemDetail.click()
    await page.getByRole('option', { name: '名称', exact: true }).click()
    await expect(preview).not.toContainText('CAPTAIN FULL BODY')
    await expect(preview).toContainText('港口人物 (Character / important / name)')
    await expect(characterCard).toBeVisible()
    await options.click()
    await itemDetail.click()
    await page.getByRole('option', { name: '继承 · 全文', exact: true }).click()
    await expect(preview).toContainText('CAPTAIN FULL BODY')
    await editor.evaluate(node => { node.scrollTop = 0 })
    expect((await section.locator(':scope > div').first().boundingBox())!.height).toBeLessThan(50)
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-wide.png`) })
    // Collapsed cards keep group management available and preserve saved order.
    await doc.getByRole('button', { name: '全部展开', exact: true }).click()
    await doc.getByRole('button', { name: '全部收起', exact: true }).click()
    await expect(section.getByRole('button', { name: '关联资料', exact: true })).toBeHidden()
    await doc.getByRole('button', { name: '添加分组', exact: true }).click()
    const second = section.filter({ has: page.getByRole('button', { name: '编辑分组：分组 2', exact: true }) })
    await expect(second.getByRole('button', { name: '关联资料', exact: true })).toBeVisible()
    await second.getByRole('button', { name: '展开或收起分组：分组 2', exact: true }).focus()
    await page.keyboard.press('Space')
    await expect(second.getByRole('button', { name: '展开或收起分组：分组 2', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await page.keyboard.press('ArrowUp')
    await expect(doc.getByRole('status').filter({ hasText: '移动到第 1 项' })).toHaveCount(1)
    await page.keyboard.press('Space')
    await expect(section.first()).toContainText('分组 2')
    await expect.poll(async () => (await snapshot()).guide.group_order?.[0]).toMatch(/^custom:/)
    await doc.getByRole('button', { name: '全部展开', exact: true }).click()
    await expect(section.getByRole('button', { name: '关联资料', exact: true })).toHaveCount(2)
    await second.getByRole('button', { name: '删除分组：分组 2', exact: true }).click()
    await page.getByRole('alertdialog').getByRole('button', { name: '删除', exact: true }).click()
    await expect(section).toHaveCount(1)
    // Item-side controls edit the same canonical membership and update preview.
    await section.getByRole('button', { name: '港口人物', exact: true }).click()
    await expect(page.getByTestId('lore-index-memberships')).toBeVisible()
    await page.getByTestId('lore-index-memberships').getByRole('button', { name: '所属分组', exact: true }).click()
    const memberships = page.getByRole('dialog', { name: '所属分组', exact: true })
    await memberships.getByRole('combobox', { name: '展示方式：港城设定', exact: true }).click()
    await page.getByRole('option', { name: '名称', exact: true }).click()
    await memberships.press('Escape')
    await page.getByRole('button', { name: '资料索引', exact: true }).click()
    const groupToggle = section.getByRole('button', { name: '展开或收起分组：港城设定', exact: true })
    await expect(groupToggle).toHaveAttribute('aria-expanded', 'false')
    await groupToggle.press('Enter')
    await expect(groupToggle).toHaveAttribute('aria-expanded', 'true')
    await expect(preview).not.toContainText('CAPTAIN FULL BODY')
    const stableID = (await snapshot()).guide.groups[0].id
    await section.getByRole('button', { name: '编辑分组：港城设定', exact: true }).click()
    const longName = '世界法则与叙事约束的长标题'.repeat(3)
    await page.getByRole('textbox', { name: '分组标题', exact: true }).fill(longName)
    await page.getByRole('button', { name: '完成', exact: true }).click()
    await expect.poll(async () => (await snapshot()).guide.groups[0].name).toBe(longName)
    expect((await snapshot()).guide.groups[0].id).toBe(stableID)
    for (const width of [390, 320]) {
      await page.setViewportSize({ width, height: 844 })
      await section.scrollIntoViewIfNeeded()
      expect(await doc.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
      expect((await indexToolbar.boundingBox())!.height).toBeLessThan(60)
      expect(await indexToolbar.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
      // Mobile controls retain their 44px touch targets within the single row.
      expect((await section.locator(':scope > div').first().boundingBox())!.height).toBeLessThan(60)
      await section.getByRole('button', { name: `删除分组：${longName}`, exact: true }).click()
      await page.getByRole('alertdialog').getByRole('button', { name: '取消', exact: true }).click()
      await expect(page.getByRole('alertdialog')).toBeHidden()
      await expect(section).toHaveCount(1)
      await page.screenshot({ path: testInfo.outputPath(`index-${theme}-${width}.png`) })
      await indexToolbar.getByRole('button', { name: '展开实时预览', exact: true }).click()
      await expect(preview).toBeVisible()
      await expect.poll(async () => (await previewPane.boundingBox())!.width).toBeGreaterThan(width - 2)
      await expect(preview).toContainText(longName)
      expect((await previewToolbar.boundingBox())!.height).toBeLessThan(64)
      expect(await previewToolbar.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
      await doc.getByRole('radio', { name: 'Markdown', exact: true }).click()
      await expect(preview.locator('pre')).toContainText(longName)
      await doc.getByRole('radio', { name: '阅读', exact: true }).click()
      await page.screenshot({ path: testInfo.outputPath(`index-${theme}-preview-${width}.png`) })
      await indexToolbar.getByRole('button', { name: '收起实时预览', exact: true }).click()
    }
    await page.setViewportSize({ width: 1680, height: 1000 })
    await options.click()
    await page.getByRole('dialog', { name: '加载选项：港口人物', exact: true }).getByRole('button', { name: '移出当前分组', exact: true }).click()
    await expect(characterCard).toHaveCount(0)
    await expect.poll(async () => (await entries()).find(item => item.name === '港口人物')?.index_memberships?.length ?? 0).toBe(0)
    await section.getByRole('button', { name: `删除分组：${longName}`, exact: true }).click()
    await page.getByRole('alertdialog').getByRole('button', { name: '删除', exact: true }).click()
    await expect(section).toHaveCount(0)
    await expect(preview).toContainText('摘要 港口人物')
    await expect(preview).toContainText('RESIDENT CANON BODY')
    await expect.poll(async () => (await entries()).every(i => !i.index_memberships?.length)).toBe(true)
    for (const surface of ['写作', '游戏']) {
      await sidebar.getByRole('button', { name: surface, exact: true }).click()
      await sidebar.getByRole('button', { name: '资料库', exact: true }).click()
      await page.getByRole('button', { name: '资料索引', exact: true }).click()
      await expect(preview).toContainText('摘要 港口人物')
    }
    const latestSettings = await (await request.get('/api/settings')).json()
    await request.patch('/api/settings', { data: { layer: 'user', base_revision: latestSettings.revisions.user, changes: { language: 'en-US' } } })
    await page.reload()
    await page.getByRole('button', { name: 'Lore index', exact: true }).click()
    await expect(doc.getByRole('button', { name: 'Add group', exact: true })).toBeVisible()
    await expect(indexToolbar.getByRole('button', { name: 'Hide live preview', exact: true })).toBeVisible()
    await expect.poll(async () => (await previewPane.boundingBox())!.width).toBeCloseTo(preferredWidth, 0)
    await page.screenshot({ path: testInfo.outputPath(`index-${theme}-english.png`) })
  })
}
