import { cp, readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { expect, test, type APIRequestContext, type Page } from '../support/fixtures'
import { createAndOpenBook, createStartedStory } from '../support/api'

test.beforeEach(async ({ request }) => {
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'zh-CN', theme: 'dark' } } })
})

async function createSource(request: APIRequestContext, fixture: string, id: string) {
  const response = await request.post('/api/agent-chat/projects/directory', { data: { name: id } })
  expect(response.ok(), await response.text()).toBe(true)
  const project = await response.json()
  const index = await (await request.get('/api/agent-chat/projects')).json()
  const directory = index.projects.find((item: { id: string }) => item.id === project.id).path
  for (const source of ['runtime', fixture]) {
    const fixtureDirectory = new URL('../../../internal/platform/testdata/' + source + '/', import.meta.url)
    for (const entry of await readdir(fixtureDirectory)) {
      await cp(new URL(entry, fixtureDirectory), path.join(directory, entry), { recursive: true, force: false, errorOnExist: true })
    }
  }
  const manifestPath = path.join(directory, fixture === 'tool' ? 'denova.plugin.json' : 'denova.game.json')
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  manifest.id = id
  manifest.name = { 'zh-CN': id, 'en-US': id }
  await writeFile(manifestPath, JSON.stringify(manifest))
  const sources = await (await request.get('/api/platform/manage/development')).json()
  const development = sources.find((source: { projectId: string }) => source.projectId === project.id)
  expect(development).toBeDefined()
  return { project, development }
}

async function installSource(request: APIRequestContext, fixture: string, id: string) {
  const source = await createSource(request, fixture, id)
  const checked = await request.get(`/api/platform/manage/development/${source.development.developmentId}/check`)
  expect(checked.ok(), await checked.text()).toBe(true)
  const candidate = await checked.json()
  const installed = await request.post('/api/platform/manage/packages/install', { data: { candidateId: candidate.candidateId, grants: candidate.manifest.permissions.required } })
  expect(installed.ok(), await installed.text()).toBe(true)
  return installed.json()
}

async function navigate(page: Page, name: string) {
  await page.getByLabel('工作台侧边栏').getByRole('button', { name, exact: true }).click()
}

for (const language of ['zh-CN', 'en-US'] as const) {
  test(`offers neutral plugin and game initialization in ${language}`, async ({ page, request }) => {
    const chinese = language === 'zh-CN'
    const theme = chinese ? 'dark' : 'light'
    await request.patch('/api/settings', { data: { layer: 'user', changes: { language, theme } } })
    await page.addInitScript(() => localStorage.setItem('nova:mode', 'extensions'))
    await page.route('**/api/platform/manage/catalog', route => route.fulfill({ json: [] }))
    await page.goto('/')
    const createLabel = chinese ? '创建扩展' : 'Create extension'
    const installLabel = chinese ? '安装扩展' : 'Install extension'
    const actions = page.locator('[data-slot="sidebar-header"]').filter({ has: page.getByRole('button', { name: createLabel, exact: true }) })
    await expect(actions.getByRole('button', { name: createLabel, exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: installLabel, exact: true })).toHaveCount(1)
    await actions.getByRole('button', { name: installLabel, exact: true }).click()
    await expect(page.getByRole('dialog', { name: installLabel, exact: true })).toBeVisible()
    await page.keyboard.press('Escape')
    await actions.getByRole('button', { name: createLabel, exact: true }).click()
    const create = page.getByRole('dialog', { name: createLabel })
    const templateLabel = chinese ? '模板' : 'Template'
    await expect(create.getByLabel(templateLabel, { exact: true })).toHaveCount(0)
    const types = create.getByRole('group', { name: chinese ? '扩展类型' : 'Extension type', exact: true })
    const plugin = types.getByRole('radio', { name: chinese ? '插件' : 'Plugin', exact: true })
    const game = types.getByRole('radio', { name: chinese ? '游戏' : 'Game', exact: true })
    await expect(plugin).toBeChecked()
    await game.click()
    await game.click()
    await expect(game).toBeChecked()
    await expect(plugin).not.toBeChecked()
    await create.locator('summary').filter({ hasText: chinese ? '高级选项' : 'Advanced options' }).first().click()
    await expect(create.getByLabel(templateLabel, { exact: true })).toHaveCount(0)
    const name = create.getByLabel(chinese ? '扩展名称' : 'Extension name')
    for (const width of [1440, 390]) {
      await page.setViewportSize({ width, height: 900 })
      await name.fill(width === 390 ? 'A long example project name '.repeat(8) : '')
      await page.screenshot({ path: `test-results/extension-create-${language}-${width}.png`, fullPage: true })
      const bounds = (await create.boundingBox())!
      expect(bounds.x).toBeGreaterThanOrEqual(0)
      expect(bounds.x + bounds.width).toBeLessThanOrEqual(width)
      const pluginBounds = (await plugin.boundingBox())!
      const gameBounds = (await game.boundingBox())!
      expect(pluginBounds.y).toBe(gameBounds.y)
      expect(pluginBounds.x + pluginBounds.width).toBeLessThanOrEqual(gameBounds.x)
    }
    await create.getByRole('button', { name: chinese ? '取消' : 'Cancel', exact: true }).click()
    for (const label of [createLabel, installLabel]) {
      await page.getByRole('button', { name: chinese ? '扩展目录' : 'Extensions directory', exact: true }).click()
      await expect(actions.getByRole('button', { name: label, exact: true })).toBeVisible()
      await page.screenshot({ path: `test-results/extension-directory-${language}-390.png`, fullPage: true, animations: 'disabled' })
      await actions.getByRole('button', { name: label, exact: true }).click()
      await expect(page.getByRole('dialog', { name: label, exact: true })).toBeVisible()
      await expect(page.getByRole('dialog')).toHaveCount(1)
      await page.keyboard.press('Escape')
    }
    for (const width of [390, 1440]) {
      await page.setViewportSize({ width, height: 900 })
      for (const kind of ['game', 'plugin'] as const) {
        if (width === 390) await page.getByRole('button', { name: chinese ? '扩展目录' : 'Extensions directory', exact: true }).click()
        const label = chinese ? (kind === 'game' ? '创建游戏' : '创建插件') : (kind === 'game' ? 'Create game' : 'Create plugin')
        const group = page.locator('[data-slot="sidebar-group"]').filter({ has: page.getByRole('button', { name: label, exact: true }) })
        const collapse = group.getByRole('button', { expanded: true })
        await collapse.click()
        await group.getByRole('button', { name: label, exact: true }).click()
        await expect(create).toBeVisible()
        await expect(page.getByRole('dialog')).toHaveCount(1)
        await expect(kind === 'game' ? game : plugin).toBeChecked()
        await expect(name).toHaveValue('')
        await page.keyboard.press('Escape')
        await expect(create).not.toBeVisible()
        if (width === 390) await expect(group).not.toBeVisible()
        if (width === 1440) {
          await expect(group.getByRole('button', { expanded: false })).toBeVisible()
          await group.getByRole('button', { expanded: false }).click()
        }
      }
    }
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.getByLabel(chinese ? '工作台侧边栏' : 'Workbench sidebar').getByRole('button', { name: chinese ? '工作台' : 'Workspace', exact: true }).click()
    await page.getByRole('button', { name: chinese ? '添加项目' : 'Add project', exact: true }).filter({ visible: true }).first().click()
    const directoryLabel = chinese ? '新建工作目录' : 'New working directory'
    await page.getByRole('dialog', { name: chinese ? '添加项目' : 'Add project', exact: true }).getByRole('button', { name: new RegExp(directoryLabel) }).click()
    const directory = page.getByRole('dialog', { name: directoryLabel })
    await expect(directory.getByLabel(templateLabel, { exact: true })).toHaveCount(0)
    await page.screenshot({ path: `test-results/extension-examples-${language}.png`, fullPage: true })
  })
}

test('creates from Extensions and develops, previews and installs in one workbench conversation', async ({ page, request, browserDiagnostics }) => {
  test.slow()
  browserDiagnostics.allow(/console\.error: Failed to load resource:.*404.*game-data\/file/)
  await page.addInitScript(() => localStorage.setItem('nova:mode', 'extensions'))
  // This journey checks the empty state even when other suites installed packages.
  await page.route('**/api/platform/manage/catalog', route => route.fulfill({ json: [] }))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '扩展', exact: true })).toBeVisible()
  await expect(page.getByText('尚未安装扩展', { exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/platform-empty-dark-wide.png', fullPage: true })
  await page.unroute('**/api/platform/manage/catalog')
  await page.getByRole('button', { name: '创建游戏', exact: true }).click()
  const create = page.getByRole('dialog', { name: '创建扩展' })
  await create.getByLabel('扩展名称').fill('Workbench Extension')
  await expect(create.getByRole('radio', { name: '游戏', exact: true })).toBeChecked()
  await create.locator('summary').filter({ hasText: '高级' }).first().click()
  await expect(create.getByLabel('模板', { exact: true })).toHaveCount(0)
  await create.getByLabel('你想做什么（可选）').fill('Write the Project proof. E2E_GENERAL_PROJECT_ALPHA_WRITE')
  await create.getByRole('button', { name: '创建并打开工作台' }).click()
  await expect(create).not.toBeVisible()
  await expect(page.getByRole('tab', { name: /开发 Workbench Extension/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: '扩展', exact: true })).not.toBeVisible()
  await expect(page.getByText('General Project write completed: alpha-project-only.', { exact: true }).filter({ visible: true })).toBeVisible()
  expect(await page.getByText('画面中的运行尚未准备好接收指令，请等待重新连接', { exact: true }).count()).toBe(0)
  const projects = await (await request.get('/api/agent-chat/projects')).json()
  const project = projects.projects.find((item: { name: string }) => item.name === 'Workbench Extension')
  expect(project.type).toBe('general')
  expect(project.sessions).toHaveLength(1)
  expect(await readFile(path.join(project.path, 'e2e-project-proof.txt'), 'utf8')).toBe('alpha-project-only')
  const manifestPath = path.join(project.path, 'denova.game.json')
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  expect(manifest.id).toMatch(/^extension\./)
  await page.getByRole('button', { name: '更多开发操作', exact: true }).filter({ visible: true }).click()
  await page.getByRole('menuitem', { name: '源码清单', exact: true }).click()
  const sourceEditor = page.getByRole('dialog', { name: '源码清单' })
  await sourceEditor.getByLabel('说明', { exact: true }).fill('在工作台开发的扩展')
  await expect.poll(async () => JSON.parse(await readFile(manifestPath, 'utf8')).description['zh-CN']).toBe('在工作台开发的扩展')
  await page.screenshot({ path: 'test-results/platform-development-dark-wide.png', fullPage: true })
  await sourceEditor.locator('summary').filter({ hasText: '更多信息' }).click()
  await sourceEditor.getByRole('button', { name: '编辑完整清单' }).click()
  await expect(page.getByText('denova.game.json', { exact: true }).filter({ visible: true }).first()).toBeVisible()
  const edited = JSON.parse(await readFile(manifestPath, 'utf8'))
  edited.development = { build: { command: 'node', args: ['-e', 'require("node:fs").writeFileSync("build-proof.txt", "built")'] } }
  await writeFile(manifestPath, JSON.stringify(edited), 'utf8')
  await page.getByRole('button', { name: '更多开发操作', exact: true }).filter({ visible: true }).click()
  await page.getByRole('menuitem', { name: '构建', exact: true }).click()
  const build = page.getByRole('dialog', { name: '构建' })
  await build.getByRole('button', { name: '执行构建命令' }).click()
  await expect.poll(() => readFile(path.join(project.path, 'build-proof.txt'), 'utf8').catch(() => '')).toBe('built')
  await page.keyboard.press('Escape')
  await expect(build).not.toBeVisible()
  await page.getByRole('button', { name: '发布到本机', exact: true }).filter({ visible: true }).click()
  const publication = page.getByRole('dialog', { name: '发布到本机', exact: true })
  await expect(publication.getByRole('combobox')).toHaveCount(0)
  await expect(publication.getByRole('switch')).toHaveCount(0)
  await publication.getByRole('button', { name: '确认发布', exact: true }).click()
  await expect(page.getByRole('switch', { name: '启用 Workbench Extension' })).toBeChecked()
  expect((await (await request.get('/api/platform/manage/catalog')).json()).filter((item: { id: string }) => item.id === manifest.id)).toHaveLength(1)
  await expect(page.getByRole('button', { name: '源码清单', exact: true }).filter({ visible: true })).toHaveCount(0)
  await page.getByRole('button', { name: '打开源码' }).filter({ visible: true }).click()
  await expect(page.getByRole('tab', { name: /开发 Workbench Extension/ })).toBeVisible()
  await expect(page.getByText('General Project write completed: alpha-project-only.', { exact: true }).filter({ visible: true })).toBeVisible()
  await navigate(page, '扩展')
  const plugin = await createSource(request, 'tool', 'test.import-plugin')
  const index = await (await request.get('/api/agent-chat/projects')).json()
  const directory = index.projects.find((item: { id: string }) => item.id === plugin.project.id).path
  const pluginManifestPath = path.join(directory, 'denova.plugin.json')
  await page.getByRole('button', { name: '安装扩展', exact: true }).first().click()
  const install = page.getByRole('dialog', { name: '安装扩展' })
  await install.getByRole('tab', { name: '本地文件', exact: true }).click()
  await install.getByLabel('本地包目录').fill(directory)
  await install.getByRole('button', { name: '检查作品包' }).click()
  await install.getByRole('switch', { name: /调用已声明工具/ }).click()
  await install.getByRole('button', { name: '安装扩展', exact: true }).click()
  await selectExtension(page, 'test.import-plugin')
  const settings = page.getByRole('region', { name: '使用配置与授权' }).filter({ visible: true })
  await settings.getByRole('switch', { name: '启用测试行为' }).click()
  await settings.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(settings.getByRole('button', { name: '保存设置', exact: true })).toBeDisabled()
  const savedSettings = await (await request.get('/api/platform/manage/packages/plugin/test.import-plugin/settings?locale=zh-CN')).json()
  expect(savedSettings.overrides).toEqual({ enabled: true })
  expect((await readFile(path.join(directory, 'plugin.toml'), 'utf8')).trim()).toBe('enabled = false')
  await page.getByRole('button', { name: '打开源码' }).click()
  await page.getByRole('button', { name: '试运行', exact: true }).filter({ visible: true }).click()
  await page.getByRole('button', { name: '启动试运行' }).filter({ visible: true }).click()
  await page.getByLabel('工具输入（JSON）').fill('{"text":"A🌷中"}')
  await page.getByRole('button', { name: '运行', exact: true }).filter({ visible: true }).click()
  await expect(page.locator('pre').filter({ hasText: '"value": 3' })).toBeVisible()
  const previewRuntimes = await (await request.get('/api/platform/manage/runtimes')).json()
  expect(previewRuntimes.find((runtime: { context: { environment: string; source: { package: { id: string } } } }) => runtime.context.environment === 'preview' && runtime.context.source.package.id === 'test.import-plugin').context.settings).toEqual({ enabled: false })
  await page.getByRole('button', { name: '停止', exact: true }).filter({ visible: true }).click()
  await page.getByRole('dialog', { name: '试运行', exact: true }).getByRole('button', { name: '关闭', exact: true }).first().click()
  const submitted = page.waitForRequest(request => request.method() === 'POST' && (request.postData()?.includes('E2E_DEVELOPMENT_FEEDBACK_PROBE') ?? false))
  const composer = page.getByPlaceholder('输入消息，/ 选择命令或 Skills').filter({ visible: true })
  await composer.fill('Summarize the last tool result. E2E_DEVELOPMENT_FEEDBACK_PROBE')
  await composer.press('Enter')
  expect((await submitted).postData()).toContain('Tool test.import-plugin/probe')
  await expect(page.getByText('Deterministic E2E response completed.', { exact: true }).filter({ visible: true })).toBeVisible()
  await navigate(page, '扩展')
  await selectExtension(page, 'test.import-plugin')
  const toggle = page.getByRole('switch', { name: '启用 test.import-plugin' })
  await toggle.click()
  await expect(toggle).not.toBeChecked()
  await page.getByRole('button', { name: '管理 test.import-plugin', exact: true }).click()
  await page.getByRole('menuitem', { name: '卸载', exact: true }).click()
  await page.getByRole('dialog', { name: '卸载' }).getByRole('button', { name: '卸载', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'test.import-plugin', exact: true })).not.toBeVisible()
  const retained = await (await request.get('/api/agent-chat/projects')).json()
  expect(retained.projects.find((item: { id: string }) => item.id === plugin.project.id).sessions).toHaveLength(1)
  expect(JSON.parse(await readFile(pluginManifestPath, 'utf8')).id).toBe('test.import-plugin')
})

async function selectExtension(page: Page, name: string) {
  await page.locator('[data-slot="sidebar-menu-button"]').filter({ hasText: name, visible: true }).click()
  await expect(page.getByRole('heading', { name, exact: true }).filter({ visible: true })).toBeVisible()
}

test('edits extension settings through bilingual forms with persistent defaults', async ({ page, request, browserDiagnostics }) => {
  browserDiagnostics.allow(/console\.error:.*(400|configuration operation failed)/)
  const release = await installSource(request, 'static', 'test.settings-ui')
  await installSource(request, 'static', 'test.settings-other')
  await page.addInitScript(() => localStorage.setItem('nova:mode', 'extensions'))
  await page.goto('/')
  await selectExtension(page, 'test.settings-ui')
  const settings = page.getByRole('region', { name: '使用配置与授权' }).filter({ visible: true })
  await expect(settings.getByRole('switch', { name: '显示标签' })).toBeChecked()
  await settings.getByRole('combobox', { name: '显示方式' }).click()
  await page.getByRole('option', { name: '完整', exact: true }).click()
  await settings.getByRole('switch', { name: '显示标签' }).click()
  await expect(page.getByRole('dialog', { name: '使用配置与授权' })).toHaveCount(0)
  await expect(settings.getByRole('tab')).toHaveCount(0)
  await settings.getByRole('switch', { name: '使用选定模型生成内容', exact: true }).click()
  await selectExtension(page, 'test.settings-other')
  await expect(settings.getByRole('switch', { name: '显示标签' })).toBeChecked()
  await settings.getByRole('switch', { name: '显示标签' }).click()
  await selectExtension(page, 'test.settings-ui')
  await expect(settings.getByRole('switch', { name: '使用选定模型生成内容', exact: true })).toBeChecked()
  await settings.getByRole('button', { name: '保存权限', exact: true }).click()
  await expect(settings.getByRole('button', { name: '保存权限', exact: true })).toBeDisabled()
  await settings.getByRole('switch', { name: '使用选定模型生成内容', exact: true }).click()
  await settings.getByRole('button', { name: '保存权限', exact: true }).click()
  await expect(settings.getByRole('button', { name: '保存权限', exact: true })).toBeDisabled()
  await selectExtension(page, 'test.settings-other')
  await expect(settings.getByRole('switch', { name: '显示标签' })).not.toBeChecked()
  await settings.getByRole('button', { name: '取消', exact: true }).click()
  await selectExtension(page, 'test.settings-ui')
  await expect(settings.getByRole('combobox', { name: '显示方式' })).toHaveText('完整')
  for (const destination of ['写作', '游戏']) {
    await navigate(page, destination)
    await navigate(page, '扩展')
    await expect(settings.getByRole('switch', { name: '显示标签' })).not.toBeChecked()
    await expect(settings.getByRole('combobox', { name: '显示方式' })).toHaveText('完整')
  }
  await page.screenshot({ path: 'test-results/platform-settings-dark-wide.png', fullPage: true })
  const initial = await (await request.get('/api/platform/manage/packages/game/test.settings-ui/settings')).json()
  const rejected = await request.put('/api/platform/manage/packages/game/test.settings-ui/settings', { data: {
    releaseId: release.ref.releaseId, expectedRevision: initial.revision, overrides: { display: { variant: 'invalid' } },
  } })
  expect(rejected.status()).toBe(400)
  await expect(settings.getByRole('combobox', { name: '显示方式' })).toHaveText('完整')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/platform-settings-dark-narrow.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await settings.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(settings.getByRole('button', { name: '保存设置', exact: true })).toBeDisabled()
  const saved = await (await request.get('/api/platform/manage/packages/game/test.settings-ui/settings?locale=en-US')).json()
  expect(saved.values).toEqual({ display: { variant: 'full', showLabel: false } })
  expect(saved.releaseId).toBe(release.ref.releaseId)
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'en-US', theme: 'light' } } })
  await page.evaluate(() => { localStorage.setItem('theme', 'light'); localStorage.setItem('nova.locale.configured', 'en-US') })
  await page.reload()
  await page.setViewportSize({ width: 1440, height: 900 })
  await selectExtension(page, 'test.settings-ui')
  const english = page.getByRole('region', { name: 'Usage settings and permissions' }).filter({ visible: true })
  await expect(english.getByRole('switch', { name: 'Show label' })).not.toBeChecked()
  await expect(english.getByRole('combobox', { name: 'Display variant' })).toHaveText('Full')
  await expect(english).not.toContainText('显示标签')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/platform-settings-light-narrow.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/platform-settings-light-wide.png', fullPage: true })
  await english.getByRole('button', { name: 'Restore defaults' }).click()
  await english.getByRole('button', { name: 'Save settings', exact: true }).click()
  await expect(english.getByRole('button', { name: 'Save settings', exact: true })).toBeDisabled()
  expect((await (await request.get('/api/platform/manage/packages/game/test.settings-ui/settings')).json()).overrides).toEqual({})
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'zh-CN', theme: 'dark' } } })
})

test('shows frozen installed metadata with source links across themes and screen sizes', async ({ page, request }) => {
  const first = await createSource(request, 'tool', 'test.directory-first')
  await createSource(request, 'static', 'test.directory-second')
  const index = await (await request.get('/api/agent-chat/projects')).json()
  const sourcePath = index.projects.find((project: { id: string }) => project.id === first.project.id).path
  const manifestPath = path.join(sourcePath, 'denova.plugin.json')
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  manifest.name['zh-CN'] = '这是一个用于检查二级目录和配置页排版的很长很长的扩展名称'.repeat(3)
  await writeFile(manifestPath, JSON.stringify(manifest))
  const checked = await (await request.get(`/api/platform/manage/development/${first.development.developmentId}/check`)).json()
  const installed = await request.post('/api/platform/manage/packages/install', { data: { candidateId: checked.candidateId, grants: checked.manifest.permissions.required } })
  expect(installed.ok(), await installed.text()).toBe(true)
  await page.addInitScript(() => localStorage.setItem('nova:mode', 'extensions'))
  await page.goto('/')
  await selectExtension(page, manifest.name['zh-CN'])
  await writeFile(manifestPath, JSON.stringify({ ...manifest, version: '2.0.0', name: { ...manifest.name, 'zh-CN': 'Uninstalled draft' } }))
  await page.reload()
  await selectExtension(page, manifest.name['zh-CN'])
  await page.getByRole('textbox', { name: '搜索扩展' }).fill('no matching extension')
  await expect(page.getByText('未找到扩展', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '清除搜索', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '搜索扩展' })).toHaveValue('')
  await expect(page.getByRole('button', { name: /\d+ 个版本/, exact: true })).toHaveCount(0)
  await expect(page.locator('article').filter({ visible: true }).getByText('v1.0.0', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: `管理 ${manifest.name['zh-CN']}`, exact: true }).click()
  await page.getByRole('menuitem', { name: '卸载', exact: true }).click()
  const uninstall = page.getByRole('dialog', { name: '卸载', exact: true })
  await uninstall.getByRole('button', { name: '取消', exact: true }).click()
  await expect(uninstall).toBeHidden()
  await expect(page.getByRole('switch', { name: `启用 ${manifest.name['zh-CN']}`, exact: true })).toBeChecked()
  await expect(page.getByText('Uninstalled draft', { exact: true })).not.toBeVisible()
  await expect(page.getByText('test.directory-second', { exact: true })).not.toBeVisible()
  await expect(page.getByRole('button', { name: '构建', exact: true }).filter({ visible: true })).toHaveCount(0)
  await expect(page.getByRole('region', { name: '使用配置与授权' }).filter({ visible: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '使用配置与授权' })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/platform-installed-dark-wide.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/platform-long-title-dark-narrow.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'en-US', theme: 'light' } } })
  await page.evaluate(() => { localStorage.setItem('theme', 'light'); localStorage.setItem('nova.locale.configured', 'en-US') })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Extensions', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/platform-installed-light-narrow.png', fullPage: true })
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/platform-installed-light-wide.png', fullPage: true })
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'zh-CN', theme: 'dark' } } })
})

test('chooses game types and stops disabled games while preserving their saves', async ({ page, request, browserDiagnostics }) => {
  test.slow()
  browserDiagnostics.allow(/console\.error: Failed to load resource:.*404.*game-data\/file/)
  const book = await createAndOpenBook(request, 'Mixed Game Stories')
  await createStartedStory(request, 'Original interactive story')
  await installSource(request, 'static', 'test.story-state')
  await page.goto('/')
  await navigate(page, '游戏')
  await expect(page.getByPlaceholder(/你要做什么/)).toBeVisible()
  await expect(page.getByRole('button', { name: '进入', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '新建', exact: true }).filter({ visible: true }).click()
  await page.getByLabel('游戏类型').click()
  await page.getByRole('option', { name: 'test.story-state', exact: true }).click()
  await page.getByRole('button', { name: '设为默认' }).click()
  await expect(page.getByRole('button', { name: '默认游戏' })).toBeDisabled()
  await page.getByLabel('故事线名称（可选）').fill('Storage storyline')
  await page.getByRole('spinbutton', { name: '初始数值' }).fill('0')
  await page.getByRole('button', { name: '创建故事线', exact: true }).click()
  const frame = page.frameLocator('iframe[title="游戏画面"]')
  await expect(frame.getByRole('button', { name: '保存测试数据' })).toBeEnabled()
  await frame.getByRole('button', { name: '保存测试数据' }).click()
  await expect(frame.locator('[role="status"]')).toHaveText('测试数据已保存')
  const saves = await (await request.get('/api/platform/manage/instances')).json()
  const save = saves.find((item: { title: string }) => item.title === 'Storage storyline')
  expect(save).toMatchObject({ projectId: book.projectId, preview: false })
  await page.screenshot({ path: 'test-results/platform-game-dark-wide.png', fullPage: true })
  await navigate(page, '扩展')
  await selectExtension(page, 'test.story-state')
  const toggle = page.getByRole('switch', { name: '启用 test.story-state' })
  await toggle.click()
  await expect(toggle).not.toBeChecked()
  expect((await (await request.get('/api/platform/manage/runtimes')).json()).some((item: { id: string }) => item.id === save.instanceId)).toBe(false)
  expect(await (await request.get('/api/platform/manage/game-preferences')).json()).toEqual({ defaultGameId: 'builtin.story' })
  await navigate(page, '游戏')
  await expect(page.getByText('此游戏已停止，请退出后继续游玩。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '故事与存档', exact: true }).click()
  await page.getByRole('button', { name: '退出并停止' }).click()
  await expect(page.getByRole('button', { name: '继续游玩' })).toBeDisabled()
  await navigate(page, '扩展')
  await toggle.click()
  await expect(toggle).toBeChecked()
  await navigate(page, '游戏')
  await expect(frame.locator('#value')).toHaveText('1')
  await frame.getByRole('button', { name: '保存测试数据' }).click()
  await expect(frame.locator('#value')).toHaveText('2')
  await page.getByRole('button', { name: '故事与存档', exact: true }).click()
  await page.getByRole('button', { name: '选择故事线', exact: true }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'Original interactive story', exact: true }).click()
  await expect(page.getByPlaceholder(/你要做什么/)).toBeVisible()
  expect((await (await request.get(`/api/platform/manage/instances/${save.instanceId}`)).json()).releaseId).toBe(save.releaseId)
  const projects = await (await request.get('/api/agent-chat/projects')).json()
  const directory = projects.projects.find((item: { name: string }) => item.name === 'test.story-state').path
  const server = path.join(directory, 'server.mjs')
  await writeFile(server, await readFile(server, 'utf8') + '\n// Same-version game update.\n')
  const candidate = await (await request.post('/api/platform/manage/packages/preview', { data: { directory } })).json()
  const updated = await request.post('/api/platform/manage/packages/install', { data: { candidateId: candidate.candidateId, grants: candidate.manifest.permissions.required } })
  expect(updated.ok(), await updated.text()).toBe(true)
  await navigate(page, '扩展')
  await navigate(page, '游戏')
  await page.getByRole('button', { name: '选择故事线', exact: true }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'Storage storyline', exact: true }).click()
  await expect(frame.locator('#value')).toHaveText('2')
  await expect(page.getByRole('combobox', { name: '切换版本' })).toHaveCount(0)
  await page.getByRole('button', { name: '故事与存档', exact: true }).click()
  await page.getByRole('button', { name: '使用已安装的更新', exact: true }).click()
  const review = page.getByRole('dialog', { name: '使用已安装的更新', exact: true })
  await review.getByRole('button', { name: '确认', exact: true }).click()
  await expect(review).not.toBeVisible()
  expect((await (await request.get(`/api/platform/manage/instances/${save.instanceId}`)).json()).releaseId).toBe(candidate.digest)
  await page.getByRole('button', { name: '继续游玩', exact: true }).click()
  await expect(frame.locator('#value')).toHaveText('2')
  await page.getByRole('button', { name: '故事与存档', exact: true }).click()
  await page.getByRole('button', { name: '选择故事线', exact: true }).filter({ visible: true }).click()
  await page.getByRole('button', { name: 'Original interactive story', exact: true }).click()
  await page.getByRole('button', { name: '新建', exact: true }).filter({ visible: true }).click()
  await expect(page.getByLabel('游戏类型')).toHaveText('test.story-state')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: 'test-results/platform-story-dark-narrow.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'en-US', theme: 'light' } } })
  await page.evaluate(() => { localStorage.setItem('theme', 'light'); localStorage.setItem('nova.locale.configured', 'en-US'); localStorage.setItem('nova:mode', 'extensions') })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Extensions', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Usage settings and permissions', exact: true })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.screenshot({ path: 'test-results/platform-extensions-light-narrow.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'test-results/platform-extensions-light-wide.png', fullPage: true })
  await request.patch('/api/platform/manage/game-preferences', { data: { defaultGameId: 'builtin.story' } })
  await request.patch('/api/settings', { data: { layer: 'user', changes: { language: 'zh-CN', theme: 'dark' } } })
})
